import { GoogleGenAI } from "@google/genai";
import { GenerateContentResponse, VideosOperation } from "../../../shared/types";
import { IAIProvider, GenerateContentArgs, GenerateVideosArgs, GetVideosOperationArgs, AIProviderConfig } from "./interfaces";

/**
 * Ensures proxy settings are applied globally for undici (used by @google/genai)
 * Handles ES module dynamic import safely.
 */
let proxyInitialized = false;
async function initializeProxy() {
    if (proxyInitialized) return;
    proxyInitialized = true;
    
    const proxyUrl = process.env.HTTPS_PROXY || process.env.HTTP_PROXY || "";
    if (!proxyUrl) return;

    try {
        const { setGlobalDispatcher, ProxyAgent } = await import("undici");
        setGlobalDispatcher(new ProxyAgent(proxyUrl));
        console.log(`[GoogleProvider] Proxy configured via undici: ${proxyUrl}`);
    } catch (error) {
        console.warn("[GoogleProvider] Proxy configuration failed:", error);
    }
}

export class GoogleProvider implements IAIProvider {
    private ai: GoogleGenAI;

    constructor(config?: AIProviderConfig) {
        const apiKey = config?.apiKey || process.env.GOOGLE_API_KEY || "";
        this.ai = new GoogleGenAI({ apiKey });
    }

    async generateContent(args: GenerateContentArgs): Promise<GenerateContentResponse> {
        await initializeProxy();
        
        let { model, contents, config } = args;
        // Default to a model that solidly supports search and reasoning
        model = "gemini-3.1-flash-lite-preview"; 

        // Normalize contents for Google Native SDK
        const parsedContents = contents?.parts ? contents.parts : contents;

        const genConfig: any = {
            tools: [{ googleSearch: {} }],
        };

        if (typeof config?.temperature === "number") {
            genConfig.temperature = config.temperature;
        }

        // Format system instructions
        let systemInstruction = config?.systemInstruction ? String(config.systemInstruction) : "";

        // Handle JSON Schema conflict with Search Grounding
        // Native JSON responseMimeType conflicts with Google Search Grounding citations.
        // We gracefully degrade to Markdown JSON blocks to preserve both search & parsing logic.
        if (config?.responseSchema || config?.responseMimeType === "application/json") {
            systemInstruction += `\n\n[FORMATTING INSTRUCTION]\nYou must output your response strictly as a valid JSON object wrapped in a \`\`\`json\`\`\` markdown block. Any search grounding references or footnotes generated by the system MUST be placed strictly outside the markdown block. However, if your JSON schema requires fields like 'video_url', you MUST explicitly write the specific web URLs you found during your search directly into those JSON fields.\n`;
            
            if (config?.responseSchema) {
                systemInstruction += `\nExpected JSON Schema:\n${JSON.stringify(config.responseSchema, null, 2)}`;
            }
        }

        if (systemInstruction) {
            genConfig.systemInstruction = systemInstruction;
        }

        const response = await this.ai.models.generateContent({
            model,
            contents: parsedContents,
            config: genConfig
        });

        const text = response.text || "";
        
        return {
            text,
            candidates: [{ content: { parts: [{ text }] } }]
        };
    }

    async generateVideos(args: GenerateVideosArgs): Promise<VideosOperation> {
        throw new Error("generateVideos is not implemented for Google native provider. Use t8star/polo.");
    }

    async getVideosOperation(args: GetVideosOperationArgs): Promise<VideosOperation> {
        throw new Error("getVideosOperation is not implemented for Google native provider. Use t8star/polo.");
    }

    async speech(body: any): Promise<ArrayBuffer> {
        throw new Error("speech is not implemented for Google native provider. Use t8star/polo.");
    }
}
