
export interface Lens {
  id: string;
  name: string;
  description: string; // Combined function & narrative role
  keywords: string;
  difficulty?: string;
}

const l = (id: string, name: string, description: string, keywords: string, difficulty?: string): Lens => ({
  id, name, description, keywords, difficulty
});

export const CORE_LENSES: Lens[] = [
  // Part 1: Foundation (001-040)
  l("001", "大特写 (Extreme Close-Up)", "【强调细节/压迫感】 极度聚焦于局部的细节（如眼睛、嘴唇、手指动作），用于展示强烈的情绪波动（瞳孔放大）、关键线索（手指上的血迹）或制造令人窒息的压迫感。", "Extreme close-up, Macro detail, Iris texture, Pores visible", "Low"),
  l("002", "特写 (Close-Up)", "【情感连接/内心世界】 标准的“肖像镜头”。完全聚焦于人物面部，捕捉微表情变化。用于关键对话、情绪反应或让观众与角色建立强烈的情感共鸣。背景通常被虚化。", "Close-up shot, Face framing, Headshot, Emotional focus", "Low"),
  l("003", "宽特写 (Wide Close-Up)", "【舒适的亲密感】 构图范围从头顶到锁骨/肩膀。比标准特写略宽松，允许少量背景信息进入，常用于较轻松的对话或展示人物的妆造细节。", "Wide close-up, Loose headshot, Shoulder up", "Low"),
  l("004", "窒息特写 (Choker Shot)", "【焦虑/对峙】 构图切掉人物的额头和下巴，只保留眼、鼻、嘴的核心区域。制造极度的心理焦虑、幽闭恐惧或对峙时的紧张感。", "Choker shot, Face cropping forehead and chin, Intense gaze, Claustrophobic", "Med"),
  l("005", "胸景 (Medium Close-Up)", "【叙事/采访】 从头顶到胸部。这是新闻采访、纪录片或标准对话中最常用的景别。既能看清表情，又能展示肢体语言（如手势），信息量平衡。", "Medium close-up, Chest up, Bust shot, Interview framing", "Low"),
  l("006", "中景 (Medium Shot)", "【互动/关系】 从头顶到腰部。用于展示人物的上半身动作和周围环境的关系。常用于两人对话、肢体冲突或展示角色的职业状态（如正在工作的厨师）。", "Medium shot, Waist up, Mid-shot, Action interaction", "Low"),
  l("007", "牛仔景 (Cowboy Shot)", "【自信/备战】 从头顶到大腿中部。源自西部片，为了展示腰间的配枪。现在用于展示角色的自信、准备行动的状态（如手插口袋、手按在桌上）或展示服装造型。", "Cowboy shot, American shot, Thighs up, Confident stance", "Med"),
  l("008", "全景 (Full Shot)", "【全身/姿态】 展示人物从头到脚的完整形象。用于介绍角色的服装、体态、步态，或展示人物与周围环境的大小比例关系。", "Full body shot, Head to toe, Entire figure, Walking shot", "High"),
  l("009", "小全景 (Tight Full Shot)", "【紧凑全身】 全身刚好顶天立地，没有多余的空间。强调人物的高大、存在感，或者用于竖屏短剧中的全身展示。", "Tight full shot, Framing subject tightly, Vertical dominance", "High"),
  l("010", "远景 (Wide Shot)", "【环境/孤立】 人物约占画面的 1/3 或更少。重点在于展示人物所处的环境（如空旷的街道、巨大的房间）。常用于表达孤独、渺小或交代场景位置。", "Wide shot, Environment context, Subject in surroundings, Isolation", "Med"),
  l("011", "大远景 (Extreme Wide Shot)", "【史诗/渺小】 人物只是一个微小的点。用于展示宏大的自然景观（沙漠、雪山、城市天际线）或强调人在命运/自然面前的无力感。", "Extreme wide shot, Tiny figure, Massive landscape, Epic scale", "Low"),
  l("012", "建置镜头 (Establishing Shot)", "【时空定位】 通常是开场的空镜或大远景，用于交代故事发生的地点（纽约、古代皇宫）、时间（清晨、深夜）和氛围（阴森、繁华）。", "Establishing shot, City skyline, Exterior building, Location reveal", "Low"),
  l("013", "主镜头 (Master Shot)", "【场景全貌】 能够覆盖整个场景内所有角色和动作的广角镜头。通常用于建立空间关系，让观众知道谁站在哪里。", "Master shot, Scene coverage, Wide angle room view, Spatial geography", "Med"),
  l("014", "意大利式特写 (Italian Shot)", "【极度紧张/对决】 仅拍摄眼睛（眉毛到颧骨）。源自意大利西部片。用于决斗前的眼神对峙，强调角色的专注、杀气或内心的算计。", "Italian shot, Eyes only close-up, Sergio Leone style, Intense stare", "Low"),
  l("015", "过肩镜头 (Over the Shoulder)", "【对话/关系/偷窥】 越过前景人物的肩膀拍摄后景人物。用于建立两人的对话关系，让观众代入前景人物的视角，或暗示某种偷窥/监视的意味。", "Over the shoulder, OTS, Blurred foreground shoulder, Conversation", "Med"),
  l("016", "双人镜头 (Two Shot)", "【同盟/对立】 两个角色同时出现在画面中。用于展示两人的关系（亲密并肩、愤怒对视、背对背防御）。构图方式暗示了他们的心理距离。", "Two shot, Two subjects in frame, Side by side, Face to face", "Med"),
  l("017", "三人镜头 (Three Shot)", "【三角关系/群体】 三个角色同框。常用于展示复杂的三角关系、小团体的合谋或家庭场景。", "Three shot, Trio in frame, Group interaction", "High"),
  l("018", "插入镜头 (Insert Shot)", "【关键线索/强调】 切入某个物品的特写（如桌上的枪、信件上的字、时钟的指针）。用于引导观众注意关键剧情线索。", "Insert shot, Prop detail, Object focus, Clue reveal", "Low"),
  l("019", "定场航拍 (Aerial Establishing)", "【上帝视角/全知】 使用无人机或直升机拍摄的高空俯瞰镜头。用于展示巨大的地理环境、城市的布局或大规模的战争场面。", "Aerial view, Drone shot, Bird's eye view, Map view", "Low"),
  l("020", "平视 (Eye Level)", "【客观/平等/真实】 摄影机与人物眼睛高度一致。这是最中立、最自然的视角，模拟人眼的日常观察，让观众感觉真实、亲切，不带评判色彩。", "Eye level shot, Neutral angle, Straight on, Documentary style", "Low"),
  l("021", "高机位 (High Angle)", "【弱化/怜悯/孤独】 摄影机高于人物，向下拍摄。使人物看起来渺小、脆弱、受困或被审视。常用于表现角色的无助、失败或处于劣势。", "High angle shot, Looking down, Subject looks small, Vulnerable", "Low"),
  l("022", "低机位 (Low Angle)", "【强化/威严/恐惧】 摄影机低于人物，向上仰拍。使人物看起来高大、强壮、具有支配力或威胁性。常用于表现英雄气概、反派的压迫感或怪兽的巨大。", "Low angle shot, Looking up, Heroic angle, Dominant, Intimidating", "Low"),
  l("023", "俯视/上帝视角 (Top Down)", "【几何/命运/观察】 垂直向下拍摄（90度）。消除透视感，使画面变得平面化、几何化。用于展示排列整齐的物体、迷宫般的路径，或暗示一种冷酷的“天神视角”。", "Top down shot, Overhead angle, God's eye view, Flat lay, Geometry", "Low"),
  l("024", "虫视 (Worm's Eye)", "【怪诞/巨物/异化】 摄影机贴近地面向上拍摄。制造极端的透视变形，使环境看起来像压在身上。常用于表现晕倒后的视角、怪物的视角或噩梦般的氛围。", "Worm's eye view, Ground level looking up, Extreme low angle, Distorted", "Med"),
  l("025", "荷兰角 (Dutch Angle)", "【失衡/疯狂/混乱】 故意倾斜摄影机，使地平线歪斜。用于表现角色的精神错乱、醉酒、中毒，或场景中的动荡、不安和即将发生的危险。", "Dutch angle, Canted angle, Tilted horizon, Unease, Disorientation", "Low"),
  l("026", "过臀视角 (Hip Level)", "【动作/拔枪/跟随】 摄影机位于腰部高度。源自西部片拍摄拔枪动作。现在常用于动作片中的跟随镜头，强调肢体动作和手中的武器。", "Hip level shot, Camera at waist height, Gunfighter style, Action stance", "Med"),
  l("027", "膝盖视角 (Knee Level)", "【行走/细节/低调】 摄影机位于膝盖高度。用于强调人物的行走步态、鞋子细节，或展示并在低处发生的动作（如捡东西）。", "Knee level shot, Low height camera, Focus on legs, Walking detail", "Med"),
  l("028", "地面视角 (Ground Level)", "【速度/贴地/昆虫】 摄影机直接放在地面上。用于展示贴地飞行的速度感（如赛车）、爬行者的视角，或强调脚步的沉重感。", "Ground level shot, Camera on floor, Surface view, Bug eye", "Low"),
  l("029", "肩膀视角 (Shoulder Level)", "【亲密/代入/跟随】 摄影机位于肩膀高度。比平视略低，比过肩更自由。常用于跟拍镜头，让观众感觉像是走在角色身边，增强代入感。", "Shoulder level shot, Camera at shoulder height, Intimate following", "Low"),
  l("030", "主观视角 (POV)", "【代入/身临其境】 模拟角色的眼睛看到的画面。包括眨眼、视线模糊、甚至看到自己的手脚。用于让观众完全体验角色的感官。", "POV shot, First person view, Seeing through eyes, Immersive", "Med"),
  l("031", "侧面视角 (Profile Shot)", "【冷漠/隐瞒/剪影】 从正侧面（90度）拍摄人物。切断了角色与观众的眼神交流，显得冷漠、客观。常用于展示剪影轮廓，或暗示人物有所隐瞒。", "Profile shot, Side view, 90 degree angle, Silhouette, Detached", "Low"),
  l("032", "四分之三侧面 (3/4 Shot)", "【立体/经典/叙事】 介于正面和侧面之间（约45度）。这是最经典的电影拍摄角度，能展现面部的立体感，同时保留眼神交流。", "3/4 view, Three-quarter angle, Cinematic portrait, Depth", "Low"),
  l("033", "背影 (Rear View)", "【神秘/跟随/告别】 从背后拍摄人物。隐藏了面部表情，制造神秘感、悬念，或表达人物的拒绝、离去和孤独。", "Rear view, From behind, Back of head, Mystery, Walking away", "Low"),
  l("034", "天底视角 (Nadir Shot)", "【极端仰视/陷阱】 垂直正下方向上看（通常是透明地面或跳跃中）。极其罕见和怪诞的视角，用于表现人物跨过镜头，或从井底向上看。", "Nadir shot, Directly below looking up, Underneath view", "High"),
  l("035", "斜侧俯视 (Oblique High)", "【监控/偷窥/审视】 类似监控摄像头的角度（高处角落）。让人感觉场景是被监视记录的，带有一种冷冰冰的疏离感和客观性。", "Oblique high angle, CCTV perspective, Surveillance style", "Low"),
  l("036", "水平齐平 (Level Shot)", "【平衡/秩序/死板】 极其严格的水平构图，没有任何仰俯角。常用于韦斯·安德森式的对称构图，强调人工秩序、强迫症或童话感。", "Level shot, Perfectly horizontal, Symmetrical alignment, Wes Anderson style", "Low"),
  l("037", "倒置视角 (Inverted)", "【颠覆/死亡/梦境】 画面上下颠倒（180度旋转）。用于表现角色的世界观崩塌、重伤倒地后的视角，或进入奇异的梦境世界。", "Upside down camera, Inverted orientation, Disorienting, Dreamlike", "High"),
  l("038", "穿越视角 (Through-Legs)", "【羞辱/独特框架】 摄影机穿过某人的双腿拍摄后景。这是一种带有羞辱性或滑稽感的构图，也利用双腿形成了天然的画框。", "Shot through legs, Framed by legs, Unique framing, Humiliating", "High"),
  l("039", "无人机俯瞰 (Drone High)", "【全知/宏大/自由】 动态的高空视角。不仅是高，而且通常带有移动（推、拉、摇）。用于展示地理环境的连贯性或追踪车辆。", "Drone shot, Aerial view, High altitude, Sweeping view", "Low"),
  l("040", "监控视角 (CCTV Angle)", "【真实/证据/冷酷】 模拟低画质、广角畸变、带有时间码的监控画面。用于增加伪纪录片的真实感，或表现犯罪现场。", "CCTV angle, High corner shot, Wide distortion, Grainy, Security footage", "Low"),

  // Part 2: Movement (041-080)
  l("041", "静态镜头 (Static Shot)", "【客观/聚焦演技/留白】 摄影机如死般静止。剥离了一切花哨的运镜，强迫观众将全部注意力集中在画面的构图美学、光影变化或演员极其微妙的微表情上。常用于表现沉闷、绝望或极度理智的状态。", "Static camera, Tripod shot, Still shot, Absolutely no movement", "Low"),
  l("042", "左右摇摄 (Pan)", "【展示环境/转移视线】 摄影机位置不动，仅镜头向左或向右水平转动。用于向观众展示宽广的场景全貌，或者将观众的注意力从人物 A 引导到刚刚入画的人物 B 上，建立空间联系。", "Pan left, Pan right, Camera swivels horizontal, Scanning room", "Med"),
  l("043", "上下仰俯 (Tilt)", "【揭示规模/隐藏线索】 摄影机位置不动，镜头垂直向上或向下转动。向上仰(Tilt Up)常用于揭示高大建筑或巨兽的压迫感；向下俯(Tilt Down)常用于从人物面部转移到地面的关键线索（如一具尸体、一把枪）。", "Tilt up, Tilt down, Camera angles vertical, Reveal size", "Med"),
  l("044", "推镜头 (Dolly In)", "【侵入内心/顿悟/紧张】 摄影机物理上向主体缓慢推进。这是一种极具侵略性的运镜，强行将观众拉入角色的心理空间。常用于角色突然意识到某个可怕的真相（顿悟时刻），或制造即将爆发的危机感。", "Slow dolly in, Push in, Camera moves forward, Psychological tension", "Low"),
  l("045", "拉镜头 (Dolly Out)", "【抽离/孤独/全局揭示】 摄影机物理上向后退。将观众从角色的情绪中抽离出来，展示角色在巨大环境中的渺小与无助。常用于电影的结尾，或角色失去一切后的绝望时刻。", "Slow dolly out, Pull back, Camera retreats, Reveal isolation", "Low"),
  l("046", "横移跟拍 (Tracking/Truck)", "【平行伴随/时间流逝】 摄影机与运动主体保持平行的侧向移动。常用于跟随角色穿过长廊、街道，或者展示一排静止的人/物。它能保持画面的运动感，同时给予观众一种“旁观者”的冷静视点。", "Truck left, Tracking shot side view, Parallel movement", "Med"),
  l("047", "垂直升降 (Pedestal/Boom)", "【越过障碍/地位转换】 摄影机整体垂直上升或下降。上升常用于越过前景的障碍物（如墙壁）揭示后方的隐藏场景，或暗示角色灵魂的升华；下降则带来沉重感和脚踏实地的真实感。", "Pedestal up, Boom down, Vertical rise, Crane lift", "Med"),
  l("048", "光学变焦推 (Zoom In)", "【非自然强调/偷窥感】 摄影机不移动，通过转动镜头焦距放大画面。由于它压缩了空间（不像推镜头那样有物理纵深感），会产生一种非常刻意、非自然的“电视新闻”或“监控偷窥”质感。", "Zoom in, Optical zoom, Magnify focal length, Flattened depth", "Low"),
  l("049", "光学变焦拉 (Zoom Out)", "【突然抽离/语境重置】 突然拉远焦距。通常用于喜剧效果或反转，原本以为是很严肃的近景，一拉远发现角色处在一个极其滑稽或完全不同的荒诞环境中。", "Zoom out, Demagnify, Reveal context", "Low"),
  l("050", "跟随推进 (Follow Push)", "【主观代入/第三人称游戏】 摄影机紧紧跟在角色背后移动。极大地增强了代入感，观众不知道角色前方会遇到什么危险，常用于恐怖片探索长廊或英雄走向战场的背影。", "Follow shot from behind, Chasing subject, Over shoulder follow", "Low"),
  l("051", "倒退引导 (Lead Pull)", "【直面情绪/步步紧逼】 摄影机在角色正前方，角色前进，摄影机后退。这种运镜强迫观众持续盯着角色的面部表情，常用于展示角色极其坚定、愤怒或极度悲伤的行进过程。", "Leading shot, Walking backwards with subject, Frontal follow", "Low"),
  l("052", "急速横摇 (Whip Pan)", "【动作衔接/无缝转场】 摄影机极快地横向甩动，产生强烈的动态模糊。用于动作片中从一个打击动作迅速切到受击者的反应，或者作为两个不同场景之间极具动感的隐藏转场。", "Whip pan, Fast swish pan, Heavy motion blur transition, Snap pan", "High"),
  l("053", "撞击推/急推 (Crash Zoom)", "【震惊/喜剧节奏/B级片】 瞬间极其快速的变焦放大。视觉冲击力极强，通常伴随强烈的音效（如“铛！”）。用于夸张的震惊反应、发现盲点，是昆汀或邵氏武侠片常用的复古强调手法。", "Crash zoom, Snap zoom, Sudden harsh magnification, Shock reveal", "Med"),
  l("054", "手持晃动 (Handheld Shake)", "【纪实/恐慌/呼吸感】 模拟人工手持摄影机的自然抖动。消除工业打光带来的“虚假感”，使画面具有极强的战地纪录片质感。用于表现混乱的战斗、角色的惊恐发作或日常的生活流。", "Handheld camera, Camera shake, Jittery movement, Documentary style", "Low"),
  l("055", "斯坦尼康平滑 (Steadicam)", "【如丝般顺滑/梦幻漫游】 消除了一切步伐带来的震动，摄影机像幽灵一样平滑地穿梭在空间中。常用于复杂的场面调度（一镜到底），营造一种高级的工业质感或梦境般的旁观体验。", "Steadicam, Perfectly smooth movement, Floating stabilized, Gliding", "Low"),
  l("056", "漂浮游离 (Floating/Drift)", "【失重/醉意/不可控】 摄影机像在水下或太空中一样缓慢、无规律地漂移。常用于表现角色吸毒后的迷幻状态、即将昏迷前的视线，或者幽灵游荡在房间里的超自然视角。", "Floating camera, Slow random drift, Weightless movement, Ethereal", "Low"),
  l("057", "震颤聚焦 (Shaky Zoom)", "【突发新闻/极度不安】 结合了手持的剧烈晃动和不断的来回变焦寻找焦点。极度破坏画面的稳定性，常用于灾难降临瞬间（如外星飞船砸下）或狗仔队偷拍视角的紧张感。", "Shaky camera zoom, Hunting for focus, Chaotic news footage style", "Low"),
  l("058", "随机漫游 (Searching Pan)", "【迷失/寻找/心理盲区】 摄影机漫无目的地缓慢扫视房间，似乎在寻找什么，但焦点又不在任何具体事物上。用于制造极强的心理悬念，观众会一直担心镜头边缘会突然窜出恐怖的东西。", "Meandering camera, Aimless panning, Searching movement, Uneasy wandering", "Low"),
  l("059", "旋转晕眩 (Dutch Roll)", "【失控/世界倾覆】 摄影机沿着 Z 轴（视线方向）缓慢或快速旋转。彻底打破观众的重力感知，用于表现飞机坠毁的机舱、角色精神彻底崩溃，或进入异次元空间的扭曲感。", "Camera roll, Rotating frame slowly, World spinning, Disorientation", "High"),
  l("060", "希区柯克变焦 (Dolly Zoom)", "【终极心理扭曲】 摄影机向后拉的同时镜头向前变焦（或相反），导致主体大小不变，但背景空间剧烈压缩或拉伸。这是电影史上最经典的表达“惊悚、顿悟、眩晕或超自然现象”的高阶镜头。", "Dolly zoom, Vertigo effect, Zolly, Push pull zoom, Background warping", "Extreme"),
  l("061", "360度环绕 (Orbit / Arc)", "【英雄时刻/被包围/史诗感】 摄影机围绕角色做 360 度圆周运动。顺时针环绕常带来英雄觉醒的史诗感（迈克尔·贝常用）；如果是被敌人包围，则带来无死角的压迫和绝望感。", "360 degree orbit shot, Circular camera move around subject, Heroic arc", "High"),
  l("062", "半弧形运动 (Half Arc)", "【转变/展现空间立体感】 围绕主体移动半圈（180度）。比 360 度更克制，常用于双人对话时，从一个人背后转到另一个人背后，暗示权力的转移或立场的反转。", "180 degree arc shot, Semi-circle movement, Revealing backside", "Med"),
  l("063", "蟹行横移 (Crab Dolly)", "【环境穿梭/复杂调度】 摄影机并非直线横移，而是沿着弯曲的轨道（像螃蟹一样）侧滑，穿过树林或人群的缝隙。极大地增强了空间的三维立体感和层次感。", "Crab shot, Curved tracking, Moving laterally through obstacles", "High"),
  l("064", "螺旋升降 (Corkscrew)", "【神性陨落/命运漩涡】 摄影机一边垂直升降，一边进行圆周旋转。向上螺旋带有强烈的宗教升华感或献祭感；向下螺旋俯冲则带来不可阻挡的坠落与毁灭感。", "Corkscrew camera move, Spiral up and rotate, Swirling descent", "High"),
  l("065", "无人机俯冲 (Drone Dive)", "【极速/上帝视角的打击】 从极高空以极快的速度向地面目标俯冲（FPV 质感）。带来强烈的失重感和视觉刺激，常用于表现猎鹰捕食、导弹坠落或超级英雄天降。", "FPV drone dive, Fast high angle descent, Plunging towards ground", "Med"),
  l("066", "穿越缝隙 (Gap Fly-through)", "【无缝穿梭/技术炫技】 摄影机穿过极其狭窄的缝隙（如钥匙孔、破碎的窗户、两辆车之间）。利用 AI 不受物理摄影机体积限制的特点，制造流畅的空间魔法。", "Fly through gap, Passing through narrow window, Seamless spatial transition", "Med"),
  l("067", "身体挂载 (Snorricam)", "【极度主观的焦虑/剥离现实】 将摄影机固定在演员身上（通常面对脸部）。演员走动时，脸部在画面中绝对静止，而背景剧烈晃动退后。完美表现醉酒、吸毒、中弹后的恐慌与现实剥离感。", "Snorricam, Body mount camera, Face static while background shakes violently", "Extreme"),
  l("068", "滑动变焦 (Slide Zoom)", "【诡异/非物理的观察】 摄影机向左或向右横向滑动的*同时*进行光学变焦推拉。制造出一种非常怪诞的视觉错觉，常用于恐怖片中表现空间本身的恶意。", "Truck left while zooming in, Sliding zoom, Unnatural perspective shift", "Extreme"),
  l("069", "探头揭示 (Peek Reveal)", "【偷窥/伏击/制造惊喜】 摄影机原本躲在墙壁或物体后，缓慢或突然横移，露出画面主体。用于模拟凶手的偷窥视角，或者揭示一个巨大的怪物/美丽的风景。", "Peek shot, Slow reveal from behind wall, Slide out from cover", "Med"),
  l("070", "越肩推进 (OTS Push)", "【压迫感/对话的侵略性】 在过肩镜头（OTS）的基础上，摄影机缓慢向前越过前景的肩膀，逼近后景角色的脸。暗示前景角色正在施加巨大的心理压力或步步紧逼。", "Push in over shoulder, Slow creep past foreground, Intensifying conversation", "Med"),
  l("071", "焦点转移 (Rack Focus)", "【注意力强制切换/因果关系】 摄影机位置不动，但焦点从前景（清晰变模糊）切换到后景（模糊变清晰），或反之。用于暗示前后两个事物之间的因果联系，或者让观众注意到背后潜伏的危机。", "Rack focus, Focus pull from foreground to background, Shifting attention", "High"),
  l("072", "锁定追踪 (Lock-on Stabilization)", "【机械感/赛博朋克追逐】 运用后期稳定技术，将画面的中心绝对锁定在运动角色的脸部或某个特定部位上，导致周围的环境产生极其夸张的运动模糊。极具现代工业和速度感。", "Camera mathematically locked on subject face, Stabilized tracking, Wild background blur", "Med"),
  l("073", "子弹时间 (Bullet Time Orbit)", "【时间冻结的奇观】 画面内的主体动作变得极其缓慢甚至完全静止（如停在空中的子弹），但摄影机却以正常甚至极快的速度围绕主体进行运动。极致的视觉炫技。", "Bullet time, Frozen moment in time, Camera orbiting static subject rapidly", "Extreme"),
  l("074", "贴地极速追车 (Bumper Cam)", "【危险/极速/摩擦感】 摄影机几乎贴着地面（保险杠高度）极速向前移动。强调路面的粗糙质感、轮胎的摩擦和速度带来的致命危险，动作片标配。", "Bumper cam, Extreme low angle car chase, Road vibration, High speed tracking", "Low"),
  l("075", "模拟长镜头 (Oner / Long Take)", "【沉浸/不间断的压迫力】 镜头持续时间极长，跟随角色穿越多个空间，发生多重事件而没有任何剪辑断点。要求极高的 AI 生成一致性，用于展现真实时间的流逝和不间断的紧张感。", "Continuous one-shot take, Oner, Seamless follow through multiple rooms, No cuts", "High"),
  l("076", "摇臂大横扫 (Jib Sweep)", "【开阔/宏大叙事/转场】 摄影机在半空中画出一个巨大的优美弧线，通常从一个局部细节扫过人群，最终落幅于整个大场面。极具晚会或古典史诗电影的奢华质感。", "Jib sweep, Crane arm swinging across, Sweeping cinematic motion", "Med"),
  l("077", "回旋镖运动 (Boomerang Move)", "【惊吓/确认恐惧】 摄影机快速推近某个黑暗的角落或物体，停顿一秒后，又极其快速地拉回原位。常用于恐怖片中“以为有鬼，推近看没有，松了口气”的节奏控制。", "Fast push in then immediately pull back, Yo-yo movement, Investigate and retreat", "High"),
  l("078", "视差滑动 (Parallax Slide)", "【三维立体感爆炸】 利用透视原理，摄影机横移时，确保画面中有极近的前景、中景和极远的后景。前景物体在画面中飞速划过，而后景几乎不动，极大增强画面的深度和昂贵感。", "Strong parallax effect, Dolly slide with deep foreground objects, 3D depth", "Med"),
  l("079", "突然急停 (Sudden Stop)", "【强调/物理冲击感】 摄影机在高速跟拍或推镜头的过程中，伴随着角色的动作（如撞车、被击倒、突然止步）瞬间像撞到墙一样刹车静止。极大地增加了动作的物理重量感。", "Fast tracking then sudden dead stop, Abrupt halt, Camera mimics physical impact", "Med"),
  l("080", "视线匹配移动 (Eyeline Match Move)", "【主客观融合/引导】 镜头A：角色看着画外并移动视线。镜头B：摄影机完全模仿刚才角色的视线轨迹进行移动（Pan 或 Tilt），向观众揭示角色到底看到了什么。", "Camera panning mimicking character's eyeline, Subjective scan, POV movement", "Med"),

  // Part 3: Composition (081-120)
  l("081", "三分法构图 (Rule of Thirds)", "【舒适/自然/平衡】 将画面横竖各分三份，将主体放置在交叉点上。这是最符合人类视觉习惯的构图，画面显得和谐、自然。用于大多数的标准对话和叙事场景，避免死板。", "Rule of thirds, Subject on intersection line, Balanced composition, Cinematic framing", "Low"),
  l("082", "居中构图 (Center Framing)", "【权威/神性/强迫症】 将主体严格置于画面正中央。创造一种绝对的稳定感、权威感或宗教般的庄严感。也常用于韦斯·安德森式的喜剧风格，强调一种人为的秩序。", "Center framing, Symmetrical composition, Dead center, Wes Anderson style", "Low"),
  l("083", "完全对称 (Symmetry)", "【秩序/二元对立/镜像】 画面左右两边几乎完全一致。用于表现完美的秩序、双胞胎、倒影，或者暗示某种心理上的分裂与二元对立（如善与恶）。", "Perfect symmetry, Mirror image, Symmetrical balance, Reflection", "Low"),
  l("084", "引导线 (Leading Lines)", "【视觉强制/纵深感】 利用环境中的线条（道路、栏杆、光束）将观众的视线强行引导至画面深处的主体。极大地增强画面的纵深感，让观众“走”进画面。", "Leading lines, Vanishing point, Perspective lines, Road leading to subject", "Low"),
  l("085", "框中框 (Frame within a Frame)", "【窥视/受困/层级】 利用门框、窗户、洞口等物体作为前景框住主体。制造一种“窥视”的距离感，或者暗示角色被困在某种环境/命运之中，无法逃脱。", "Frame within a frame, Shot through doorway, View through window, Natural framing", "Med"),
  l("086", "留白构图 (Negative Space)", "【孤独/思考/压抑】 主体只占画面很小一部分，其余部分是空旷的背景（天空、墙壁、黑暗）。用于表达角色的孤独、渺小，或者为即将出现的危险/文字预留空间。", "Negative space, Subject in corner, Empty background, Minimalist, Vast void", "Med"),
  l("087", "对角线构图 (Diagonal)", "【动感/不稳定/冲突】 安排主体或线条沿着对角线分布。相比水平线的稳定，对角线充满了动感和张力，常用于动作戏或表现人物内心不稳定的状态。", "Diagonal composition, Dynamic angle, Diagonal lines", "Low"),
  l("088", "L型构图 (L-Shape)", "【稳定与开放】 主体占据画面的一侧和底部（或顶部），形成 L 型。既有重量感，又保留了另一侧的开放空间，常用于展示角色与环境的互动。", "L-shape composition, Framing along edge and bottom", "High"),
  l("089", "三角形构图 (Triangle)", "【极度稳定或攻击性】 正三角形（金字塔）给人以不可动摇的稳定感（如教父）；倒三角形则给人以摇摇欲坠的危机感或攻击性（如反派压迫）。", "Triangular composition, Pyramid structure, Three subjects arrangement", "Med"),
  l("090", "S型曲线 (S-Curve)", "【优雅/流动/延展】 利用河流、道路或人物姿态形成 S 型。引导视线缓慢、优雅地穿过画面，产生一种流动的美感和深远的意境。", "S-curve path, Winding road, Serpentine line, Graceful flow", "Low"),
  l("091", "重复纹理 (Repetition)", "【工业化/非人化/压抑】 画面中充满重复的物体（如一排排士兵、一扇扇窗户）。如果主体打破这种重复，会显得极其突出；如果主体融入其中，则暗示个性的丧失。", "Repetitive pattern, Soldiers in rows, Identical windows, Industrial order", "Low"),
  l("092", "短边构图 (Short Siding)", "【封闭/没有退路】 人物面向画框边缘最近的一侧，视线受阻。制造一种压抑、紧张、没有出路或不愿意与外界交流的心理暗示。", "Short siding, Looking into edge of frame, Uncomfortable framing, Trapped", "Med"),
  l("093", "长边构图 (Long Siding)", "【开放/希望/未来】 人物面向画框边缘较远的一侧，视线前方有大量空间。暗示角色对未来有规划，或者正在期待某人/某事的到来。", "Long siding, Looking into negative space, Open composition", "Low"),
  l("094", "四象限构图 (Quadrant)", "【分割/隔离/甚至AI感】 将画面分割为四个区域，每个区域发生不同的事情，或主体只占据其中一个象限（如《黑客军团》）。制造一种疏离感和科技感。", "Quadrant framing, Mr. Robot style, Bottom corner framing, Grid composition", "Med"),
  l("095", "前景遮挡 (Foreground Bokeh)", "【偷窥/层次/甚至模糊】 在镜头前放置模糊的物体（树叶、栏杆、肩膀）。增加画面的层次感（前景-中景-后景），同时制造一种“不经意捕捉”的真实感。", "Blurred foreground object, Depth layering, Something in front, Dirty foreground", "Low"),
  l("096", "深焦摄影 (Deep Focus)", "【全知/信息量爆炸】 画面中的前景、中景、后景全部清晰。允许观众自由选择观看哪里，强调环境与人物的紧密联系，或展示复杂的场面调度。", "Deep focus, f/22, Everything sharp, Citizen Kane style", "Med"),
  l("097", "浅景深/虚化 (Shallow Focus)", "【隔离/唯美/专注】 只有主体清晰，背景极度模糊。将人物从纷乱的环境中剥离出来，强调其内心世界，或营造梦幻、唯美的视觉效果。", "Shallow depth of field, f/1.2, Bokeh background, Blurry background, Isolation", "Low"),
  l("098", "焦点搜寻 (Focus Hunting)", "【真实/捕捉/甚至失误】 模拟摄像机自动对焦或摄影师手动找焦点的过程（模糊-清晰-模糊-清晰）。极大地增强纪录片式的临场感和紧张感。", "Focus hunting, Camera searching for focus, Blur to sharp breathing", "Low"),
  l("099", "分割屈光度 (Split Diopter)", "【不可能的清晰/割裂】 (AI模拟) 画面左侧前景和右侧后景同时清晰，中间模糊。用于表现两个距离极远的角色之间强烈的心理联系或冲突，一种超现实的视觉张力。", "Split diopter shot, Sharp foreground and background, Blurry middle", "Extreme"),
  l("100", "纵深走位 (Z-Axis Staging)", "【立体调度/冲击力】 角色直接从远处走向镜头（甚至撞上镜头），或从镜头旁走向远处。最大化利用 Z 轴空间，增强画面的冲击力和三维感。", "Character walking from background to foreground, Z-axis movement, Walk into close-up", "Med"),
  l("101", "反向运动 (Counter-Move)", "【动态平衡/行云流水】 摄影机向左移，角色向右走（或反之）。这种反向运动极大地增加了画面的相对速度感和流畅度，是好莱坞大片常用的调度技巧。", "Camera pans left while subject moves right, Counter movement, Dynamic blocking", "High"),
  l("102", "平行跟随 (Parallel Tracking)", "【陪伴/审视】 摄影机与角色保持完全一致的速度同向移动。让观众感觉是角色的“影子”或“伙伴”，常用于长对话或展示行进过程。", "Tracking shot side view, Matching speed, Profile walk", "Med"),
  l("103", "环绕对峙 (Orbit Staging)", "【紧张关系/权力流动】 两个角色静止对峙，摄影机围绕他们旋转。展示他们之间紧张的张力，背景的旋转变化暗示局势的不断变化。", "360 orbit around subjects, Circular camera move, Standoff", "High"),
  l("104", "越轴 (Crossing the Line)", "【困惑/混乱/甚至错误】 故意打破 180 度轴线规则。让角色瞬间从画面左边跳到右边。用于表现角色的精神错乱、局势的瞬间反转或制造观众的生理不适。", "Crossing the 180 degree line, Disorienting jump, Axis break", "Low"),
  l("105", "推拉博弈 (Push-Pull Blocking)", "【心理攻防】 角色逼近，摄影机后退（压迫）；角色后退，摄影机逼近（追问）。通过摄影机与演员的距离变化，外化心理上的攻防战。", "Camera retreating faster than subject, Increasing distance, Push pull dynamic", "Med"),
  l("106", "横向交叉揭示 (Lateral Reveal)", "【转场/惊喜】 利用前景物体（如柱子、路人）横向划过画面，作为天然的剪辑点或用来揭示后方的新人物。", "Object passing in foreground, Wipe effect, Reveal transition", "Med"),
  l("107", "垂直升降揭示 (Vertical Reveal)", "【展示全貌/甚至神迹】 摄影机从角色的脚部垂直升起直到头顶甚至高空。用于展示角色的装备细节，或从局部逐渐揭示宏大的背景环境。", "Crane up revealing more, Jib shot rising, Tilt up from feet", "Med"),
  l("108", "穿窗/穿墙 (Fly Through)", "【无视物理/全知视角】 摄影机直接穿过玻璃窗、墙壁或钥匙孔进入室内。AI 视频生成的特权，带来一种鬼魂般无视物理法则的奇观感。", "Camera flying through window, Passing through gap, No clip move", "Med"),
  l("109", "视差滑动 (Parallax Slide)", "【深度感/立体扫描】 摄影机横移时，前景物体快速移动，背景物体慢速移动。利用运动视差极大地增强画面的 3D 立体感。", "Parallax effect, Dolly move side, Background shifting, 3D depth", "Med"),
  l("110", "旋转俯冲 (Corkscrew Dive)", "【坠落/混乱/战斗】 摄影机像钻头一样旋转着向下俯冲。常用于空战、跳伞或表现角色陷入疯狂的心理漩涡。", "Corkscrew camera move, Spinning dive, Spiral descent", "High"),
  l("111", "定点旋转 (Stationary Pan/Tilt)", "【观察者/监控】 摄影机位置固定，只转动云台跟随角色。像一个站在原地的观察者转头看人，带有一种客观、冷静甚至被动的视点。", "Static position panning head, Following subject, Security camera style", "Low"),
  l("112", "背撞 (Snorricam Style)", "【恐慌/醉酒/甚至被捕】 (AI模拟) 角色身体在画面中固定不动，背景剧烈晃动。模拟将摄影机绑在身上的效果，表现极度恐慌或失去理智。", "Snorricam effect, Face fixed background shaking, Subjective panic", "Extreme"),
  l("113", "跟随跌落 (Follow Fall)", "【共情/坠落感】 摄影机与角色保持同步速度一起坠落。让观众亲身体验坠落的失重感和恐惧感，而不是旁观。", "Camera falling with subject, Skydiving view, Freefall", "Med"),
  l("114", "地平线翻转 (Horizon Roll)", "【彻底颠覆/太空/深海】 摄影机旋转 180 度，天变成地，地变成天。用于表现太空行走的失重、深海潜水或世界观的彻底颠覆。", "Camera rolling 180 degrees, Upside down turn, Inverted world", "High"),
  l("115", "瞬间静止 (Sudden Stop)", "【撞击/强调/结局】 快速的运镜突然定格。用于动作戏的结尾（如一拳打在镜头上），或者作为影片的戛然而止。", "Fast move sudden stop, Abrupt halt, Freeze frame impact", "Med"),
  l("116", "搜寻运镜 (Searching Pan)", "【未知/恐惧/甚至盲人】 摄影机漫无目的地扫视，焦点不实。模拟人眼在黑暗中寻找危险，或盲人试图辨认环境的视角。", "Wandering camera, Searching panning, Unsteady focus", "Low"),
  l("117", "镜面穿越 (Mirror Through)", "【梦境/多重现实】 (AI特技) 摄影机直接推入镜子内部，进入镜中世界。用于表现穿越、回忆或人格分裂。", "Moving through mirror, Impossible transition, Mirror dimension", "Extreme"),
  l("118", "切入 (Cut-in)", "【强调/特写跳切】 在同一个场景中，瞬间跳切到某个局部的特写。用于打断节奏，强迫观众注意细节（如流汗的手心）。", "Cut-in shot, Closer angle on same action, Jump cut to detail", "Low"),
  l("119", "切出 (Cut-away)", "【隐喻/时间流逝】 在对话或动作中，切到旁边不相关的物体（如墙上的钟、窗外的鸟）。用于暗示时间的流逝、角色的走神或某种隐喻。", "Cut-away shot, Looking at something else, Clock ticking, Metaphor", "Low"),
  l("120", "反应镜头 (Reaction Shot)", "【情绪传递/无声胜有声】 不拍说话的人，拍听话的人。展示话语带来的冲击、悲伤或震惊。往往比说话本身更有力量。", "Reaction shot, Listening face, Shocked response, Emotional impact", "Low"),

  // Part 4: Lighting (121-160)
  l("121", "硬光 (Hard Light)", "【强硬/残酷/真实】 产生边缘清晰的阴影，对比度极高。用于表现严酷的环境（正午沙漠）、冷酷的角色性格，或者强调物体表面的粗糙质感。", "Hard light, Sharp shadows, Direct sunlight, High contrast", "Low"),
  l("122", "柔光 (Soft Light)", "【唯美/浪漫/善良】 光线经过漫反射，几乎没有阴影。用于美化人物皮肤（消除瑕疵）、营造浪漫温馨的氛围，或者表现角色的无辜与纯洁。", "Soft light, Diffused lighting, Cloudy day, Softbox, Flattering", "Low"),
  l("123", "体积光/丁达尔 (Volumetric Lighting)", "【神性/史诗/尘埃】 光线在空气中形成可见的光束（God Rays）。用于营造史诗般的氛围、神圣的时刻，或者废弃空间中尘土飞扬的真实质感。", "Volumetric lighting, God rays, Light shafts, Foggy light, Atmospheric", "Low"),
  l("124", "剪影 (Silhouette)", "【神秘/匿名/形式感】 主体背对强光，变成全黑的轮廓。用于隐藏角色身份、强调肢体动作的线条美，或者在结局时表现人物走向光明的决绝。", "Silhouette, Black figure, Bright background, Backlit", "Low"),
  l("125", "轮廓光/发丝光 (Rim Light)", "【分离/立体/英雄】 在人物背后打光，勾勒出头部和肩膀的亮边。用于将深色衣服的角色从黑暗背景中分离出来，增加立体感和“主角光环”。", "Rim lighting, Edge lighting, Hair light, Backlight separation", "Low"),
  l("126", "伦勃朗光 (Rembrandt Lighting)", "【经典/戏剧/深沉】 主光在暗部脸颊形成一个倒三角形亮区。电影中最经典的布光，赋予角色油画般的质感、立体感和深沉的内心世界。", "Rembrandt lighting, Triangle of light on cheek, Cinematic portrait", "Med"),
  l("127", "分割光/阴阳脸 (Split Lighting)", "【冲突/双重人格/邪恶】 光线从正侧面照射，半张脸亮半张脸黑。用于表现角色内心的善恶冲突、隐藏秘密，或直接暗示反派身份。", "Split lighting, Half face in shadow, Side lighting, High contrast", "Low"),
  l("128", "蝴蝶光 (Butterfly Lighting)", "【美颜/时尚/魅惑】 主光来自正上方稍高处，在鼻子下方形成蝴蝶状阴影。好莱坞黄金时代女星专用布光，能瘦脸并突出颧骨，极具魅力。", "Butterfly lighting, Paramount lighting, Shadow under nose, Glamour", "Low"),
  l("129", "明暗对照法 (Chiaroscuro)", "【极度戏剧/黑色电影】 强调亮部与暗部的极端对比，大部分画面处于黑暗中。用于黑色电影（Film Noir），营造悬疑、压抑和未知的恐惧感。", "Chiaroscuro, Deep shadows, High contrast, Film noir style", "Med"),
  l("130", "底光/鬼光 (Under Lighting)", "【恐怖/怪诞/邪恶】 光源来自脸部下方（如手电筒照下巴）。产生反自然的阴影（眼窝亮、额头黑），用于恐怖片中的鬼怪或角色发疯的时刻。", "Under lighting, Monster lighting, Up-lighting from chin, Horror", "Low"),
  l("131", "顶光 (Top Light)", "【审讯/压抑/神罚】 光源来自正头顶。眼窝深陷变成黑洞。用于审讯室场景，表现角色的疲惫、被压迫或如同骷髅般的死亡气息。", "Top lighting, Overhead light, Deep eye sockets, Interrogation", "Low"),
  l("132", "实用光 (Practical Lighting)", "【真实/生活流】 光源来自场景内的实体道具（台灯、蜡烛、屏幕）。增加场景的真实可信度，让光线看起来是有逻辑来源的。", "Practical lighting, Lamp in shot, Candle light, Diegetic light", "Med"),
  l("133", "霓虹光 (Neon/Cyberpunk)", "【未来/迷乱/科技】 高饱和度的彩色光源（粉/蓝/紫）。用于赛博朋克风格、夜店场景，表现科技感、诱惑或迷失的城市夜生活。", "Neon lighting, Cyberpunk lights, Pink and blue, Fluorescent", "Low"),
  l("134", "频闪光 (Strobe Light)", "【混乱/动感/惊悚】 光线快速闪烁。用于迪厅狂欢、动作戏的慢动作分解，或恐怖片中怪物忽隐忽现的惊悚效果。", "Strobe light, Flashing light, Pulsing, Disorienting", "Med"),
  l("135", "火光 (Firelight)", "【温暖/原始/危险】 橙红色的跳动光源。用于露营时的温馨谈话，或者火灾场景中的危险与破坏。光影的摇曳感能增加画面的动态。", "Lit by fire, Flickering warm light, Bonfire glow, Torch", "Low"),
  l("136", "屏幕光 (Screen Glow)", "【现代/冷漠/黑客】 蓝白色的冷光照亮脸部，周围黑暗。用于表现现代人的孤独、黑客工作或面对坏消息时的苍白脸色。", "Face lit by phone screen, Blue monitor glow, Computer reflection", "Low"),
  l("137", "黄金时刻 (Golden Hour)", "【唯美/希望/回忆】 日落前或日出后的一小时。光线呈金黄色，柔和且角度低，拉出长长的影子。用于表达希望、浪漫或怀旧的回忆。", "Golden hour, Warm glow, Low sun, Long shadows, Magic hour", "Low"),
  l("138", "蓝调时刻 (Blue Hour)", "【忧郁/静谧/过渡】 日落后天全黑前。天空呈深蓝色，城市灯光刚亮。用于表达孤独、冷静、等待或暧昧不清的情感状态。", "Blue hour, Twilight, Deep blue sky, Melancholy, Cold tone", "Low"),
  l("139", "高调 (High Key)", "【快乐/天堂/梦境】 画面极其明亮，几乎没有阴影。用于喜剧、天堂场景、回忆中的美好时刻或过度曝光的梦境。", "High key lighting, Bright, Overexposed style, No shadows, Heavenly", "Low"),
  l("140", "低调 (Low Key)", "【悬疑/恐惧/隐藏】 画面大部分是黑色的，只有少量高光勾勒轮廓。用于惊悚片、潜行场景或隐藏人物真实意图。", "Low key lighting, Darkness, Shadows dominant, Mystery", "Low"),
  l("141", "生物荧光 (Bioluminescence)", "【奇幻/异星/神秘】 动植物自身发出的微弱冷光（如阿凡达）。用于构建外星生态、深海环境或魔法森林。", "Bioluminescent, Glowing plants, Blue glow in dark, Magical", "Low"),
  l("142", "百叶窗影 (Gobo/Blinds)", "【黑色电影/窥视/牢笼】 光线穿过百叶窗在墙上或脸上投下条纹阴影。经典的黑色电影视觉符号，暗示被监视、内心矛盾或如同身处牢笼。", "Shadow of blinds, Gobo pattern, Striped shadows, Film noir", "Low"),
  l("143", "眼神光 (Catchlight)", "【生动/灵魂/眼泪】 在人物眼球上形成的小亮点。没有眼神光的人像“死鱼眼”；有眼神光则显得生动、含泪或充满希望。", "Catchlight in eyes, Sparkle in eyes, Reflection in pupil", "Med"),
  l("144", "镜头光斑 (Lens Flare)", "【真实感/科幻/刺眼】 强光直射镜头产生的光晕。JJ·艾布拉姆斯风格。用于增强科幻感、表现阳光的刺眼或增加画面的“摄影机存在感”。", "Lens flare, Optical flare, Sun flare, Anamorphic streak", "Low"),
  l("145", "斑驳光 (Dappled Light)", "【自然/午后/安宁】 阳光穿过树叶投下的细碎光斑。用于表现午后的宁静、公园约会或悠闲的夏日氛围。", "Dappled light, Leaf shadows, Sunlight through trees", "Low"),
  l("146", "青橙色调 (Teal & Orange)", "【商业大片/肤色突出】 暗部偏青蓝，亮部偏橙红。好莱坞最通用的调色方案，能最大程度地突出人物肤色，同时让背景显得深邃高级。", "Teal and orange, Blockbuster color grading, Blue shadows orange highlights", "Low"),
  l("147", "黑白/诺瓦 (Black & White)", "【历史/艺术/纯粹】 去除色彩，只保留光影关系。用于表现历史年代感、严肃的艺术氛围，或像《辛德勒名单》那样强调纯粹的人性。", "Black and white, Noir, Grayscale, High contrast B&W", "Low"),
  l("148", "单色调 (Monochromatic)", "【极端情绪/风格化】 画面几乎只由一种颜色构成（如全红）。全红代表极度危险/情欲；全绿代表诡异/矩阵；全蓝代表抑郁/科技。", "Monochromatic red, Single color palette, All blue scene", "Low"),
  l("149", "低饱和 (Desaturated)", "【绝望/末日/战争】 色彩灰暗，接近黑白。用于表现末日废土、战争的残酷、回忆褪色或角色内心的毫无生机。", "Desaturated, Muted colors, Bleak palette, Snyder style", "Low"),
  l("150", "高饱和 (Oversaturated)", "【疯狂/迷幻/童话】 色彩极度鲜艳，甚至刺眼。用于表现嗑药后的幻觉、疯狂的梦境、过于完美的童话世界或波普艺术风格。", "Oversaturated, Vivid colors, Technicolor, Candy colored", "Low"),
  l("151", "复古暖调 (Vintage/Sepia)", "【怀旧/记忆/西部】 泛黄的色调。用于表现回忆片段、老照片质感、西部片荒漠或温暖的家庭录像。", "Sepia tone, Vintage color grading, Old photo look, Warm haze", "Low"),
  l("152", "冷调/临床蓝 (Cold/Clinical)", "【科技/医院/隔离】 偏蓝、偏青的冷色。用于表现医院手术室、高科技实验室、寒冷的环境或人际关系的冷漠疏离。", "Cold color temperature, Blue tint, Clinical look, Sterile", "Low"),
  l("153", "暖调/琥珀 (Warm/Amber)", "【温馨/热带/墨西哥】 偏黄、偏橙的暖色。用于表现家庭聚餐、热带国家（好莱坞常用的“墨西哥滤镜”）或燥热不安的氛围。", "Warm color temperature, Amber tint, Golden atmosphere", "Low"),
  l("154", "粉彩/马卡龙 (Pastel)", "【治愈/童真/韦斯风】 低对比度、高明度的柔和色彩。韦斯·安德森标志性风格。用于表现童话、治愈系或看似可爱实则荒诞的故事。", "Pastel colors, Soft palette, Wes Anderson colors, Candy colored", "Low"),
  l("155", "矩阵绿 (Matrix Green)", "【虚拟/病态/诡异】 整体画面偏绿。用于表现虚拟世界（黑客帝国）、腐烂的环境、地下室或不健康的心理状态。", "Green tint, Matrix style, Sickly green, Fluorescent green", "Low"),
  l("156", "漂白效果 (Bleach Bypass)", "【粗砺/战争/金属感】 高对比度、低饱和度。保留了黑色和金属质感，去除柔和色彩。《拯救大兵瑞恩》风格，用于战争片或硬汉动作片。", "Bleach bypass, High contrast low saturation, Gritty, Silver retention", "Low"),
  l("157", "红外热感 (Infrared/Thermal)", "【捕猎/非人视角/异化】 模拟热成像仪的视觉（红/黄/蓝）。用于表现捕食者视角（如铁血战士）、军事无人机视角或完全异化的感知世界。", "Thermal imaging, Heat map colors, Infrared photography", "Low"),
  l("158", "霓虹配色 (Neon Palette)", "【赛博/夜生活/冲突】 紫色与青色的强烈对撞。用于表现未来的城市夜景、充满诱惑与危险的赛博朋克世界。", "Neon color palette, Purple and cyan, Synthwave style", "Low"),
  l("159", "交叉冲印 (Cross Process)", "【复古/不稳定/梦魇】 模拟胶片错误冲印的化学变色（通常暗部偏绿，亮部偏黄）。产生一种怪诞、不安、类似噩梦的复古质感。", "Cross processing, Unnatural color shift, Greenish shadows", "Med"),
  l("160", "局部彩色 (Color Isolation)", "【绝对强调/艺术化】 画面黑白，仅保留一种颜色（如红唇、红衣）。《辛德勒的名单》或《罪恶之城》风格。用于极致地强调某个象征物。", "Selective color, Black and white with one red object, Sin City style", "High"),

  // Part 5: Auteur Styles & Tech (161-200)
  l("161", "韦斯·安德森式对称 (Wes Anderson Symmetry)", "【强迫症/童话/形式感】 极致的中心对称构图，色彩通常为高明度的粉彩（Pastel）。用于表现一种人为的秩序感、荒诞的幽默或成人童话氛围。", "Wes Anderson style, Perfect symmetry, Center framing, Pastel color palette, Flat look", "Low"),
  l("162", "库布里克式凝视 (Kubrick Stare)", "【疯狂/压抑/危险】 角色头部前倾下压，眼睛向上翻看镜头。配合广角镜头，传达出极度的危险、精神错乱或即将爆发的暴力。", "Kubrick stare, Head tilted down, Eyes looking up, Creepy smile, Psychotic", "Low"),
  l("163", "库布里克一点透视 (One-Point Perspective)", "【宿命/秩序/恐怖】 强调场景深处的单一消失点（如走廊、隧道），所有线条汇聚于中心。制造一种无法逃脱的宿命感或令人不安的完美秩序。", "One point perspective, Stanley Kubrick style, Symmetrical corridor, Vanishing point center", "Low"),
  l("164", "王家卫式抽帧 (Step Printing)", "【迷离/时间流逝/孤独】 降低快门速度并复制帧（类似拖影），配合高饱和霓虹色。表现角色在喧闹城市中的孤独、时间的停滞或醉酒后的迷离感。", "Wong Kar-wai style, Step printing, Low shutter speed, Motion blur, Neon lights, Dreamy", "Med"),
  l("165", "迈克尔·贝式环绕 (Bayhem 360)", "【英雄时刻/史诗/炫技】 摄影机围绕角色做低角度的 360 度快速环绕，通常伴随慢动作起立。用于展现英雄的觉醒、集结或极具商业大片感的“装帅”时刻。", "Michael Bay style, Low angle 360 orbit, Slow motion, Heroic standing, Epic scale", "High"),
  l("166", "诺兰式旋转 (Nolan Rotation)", "【空间迷失/梦境/硬科幻】 摄影机或场景本身跟随重力发生旋转（如《盗梦空间》走廊）。用于表现物理法则的崩塌、梦境的深层或太空中的失重感。", "Christopher Nolan style, Barrel roll camera, Spinning hallway, Disorientation, Inception style", "High"),
  l("167", "塔伦蒂诺式后备箱 (Trunk Shot)", "【主观/霸气/受害者视角】 摄影机位于汽车后备箱内向上仰拍，角色低头看进来。极具辨识度的视角，暗示角色掌握了某种权力或正在审视被绑架者。", "Trunk shot, Low angle looking up, Car trunk framing, Quentin Tarantino style", "Low"),
  l("168", "维伦纽瓦式巨物 (Megastructure)", "【压迫/极简/渺小】 极简主义的巨大几何建筑与渺小的人类形成对比。配合雾气和单色调，传达出对未知力量的敬畏、压迫感和硬科幻的冷峻。", "Denis Villeneuve style, Brutalist architecture, Tiny human scale, Fog, Massive scale", "Low"),
  l("169", "雷德利·斯科特式烟雾 (Atmospheric Smoke)", "【质感/光束/未来废土】 场景中充满烟雾、灰尘和强烈的背光光束（丁达尔效应）。《银翼杀手》风格，增加画面的空气质感和视觉密度。", "Ridley Scott style, Haze, Smoke machine, Shafts of light, High contrast, Blade Runner style", "Low"),
  l("170", "芬奇式机械运镜 (Robotic Camera)", "【冷静/客观/全知】 摄影机运动如同机械臂一般精准、平滑、稳定，没有任何手持抖动。传达出一种上帝视角的冷酷、客观和不可抗拒的宿命感。", "David Fincher style, Perfectly smooth camera, No handheld, Precise movement, Dark tone", "Low"),
  l("171", "斯奈德式快慢镜 (Speed Ramp)", "【暴力美学/瞬间强调】 动作从极快瞬间切换到极慢（慢动作），展示打击细节后再恢复极快。用于强调动作的力度、肌肉线条或破坏的瞬间美感。", "Zack Snyder style, Speed ramp, Fast to super slow motion, High contrast, Action highlight", "High"),
  l("172", "阿莫多瓦式色彩 (Almodovar Color)", "【情欲/热烈/鲜艳】 画面充满高饱和度的红色、黄色等原色，极具波普艺术感。用于表达女性的激情、欲望、混乱的生活或强烈的情感冲突。", "Pedro Almodovar style, Vibrant red, Pop art colors, Passionate, Colorful interior", "Low"),
  l("173", "新海诚式光影 (Shinkai Light)", "【唯美/壁纸/粒子】 极致细腻的光影渲染，充满空气中的尘埃粒子、镜头光晕和绚丽的云彩。用于营造青春、治愈、梦幻或令人屏息的风景空镜。", "Makoto Shinkai style, Lens flare, Detailed sky, Particle effects, Anime landscape", "Low"),
  l("174", "吉卜力式风景 (Ghibli Landscape)", "【自然/手绘/宁静】 饱和度适中的手绘风格风景，强调草地、云朵和风的动态。用于表现自然的生命力、童年的怀旧感或宁静的田园生活。", "Studio Ghibli style, Painted background, Fluffy clouds, Green grass, Peaceful", "Low"),
  l("175", "赛博朋克风 (Cyberpunk)", "【高科技/低生活/霓虹】 雨夜、霓虹灯、全息广告牌、改装义体。强调视觉上的混乱与繁华，用于表现反乌托邦的未来世界。", "Cyberpunk style, Neon rain, High tech low life, Holograms, Night city", "Low"),
  l("176", "黑色电影风 (Film Noir)", "【阴影/犯罪/道德模糊】 高反差黑白或低饱和彩色，强调百叶窗阴影、烟雾和雨水。用于侦探片、悬疑片，表现人性的阴暗面。", "Film noir style, High contrast, Venetian blinds shadow, Trench coat, Mystery", "Low"),
  l("177", "伪纪录片风 (Found Footage)", "【真实/恐怖/临场】 模拟手持摄像机、夜视仪或监控画面，画质粗糙，晃动剧烈。用于恐怖片或灾难片，制造“这就发生在身边”的真实恐惧。", "Found footage, Handheld camcorder, Night vision, Grainy, POV horror", "Low"),
  l("178", "蒸汽波风 (Vaporwave)", "【复古/故障/迷幻】 80年代复古美学，粉紫色调，雕塑，Windows 95 元素。用于表现怀旧、超现实或数字时代的荒诞感。", "Vaporwave aesthetic, Purple and teal, Glitch art, Retro surrealism", "Low"),
  l("179", "极简主义风 (Minimalism)", "【纯净/抽象/孤立】 构图极其简单，大面积留白，色彩单一。用于表现极度的冷静、科技感、孤独或抽象的概念。", "Minimalist cinematography, Clean background, Single subject, Abstract shapes", "Low"),
  l("180", "暴力美学 (Heroic Bloodshed)", "【浪漫/残酷/吴宇森】 慢动作鸽子、双枪、风衣飞舞。将暴力行为艺术化、舞蹈化。用于展现兄弟情义或悲剧英雄的最后时刻。", "John Woo style, Slow motion action, Flying doves, Dual guns, Stylized violence", "Med"),
  l("181", "8K 分辨率 (8K Resolution)", "【极致清晰】 强制 AI 生成高频细节，避免画面模糊。", "8k resolution, UHD, Super detailed, Sharp focus", "Low"),
  l("182", "虚幻引擎5 (Unreal Engine 5)", "【物理光照/CGI感】 调用 UE5 的 Lumen 和 Nanite 算法风格，增强光影的物理真实感和材质细节。", "Unreal Engine 5, Lumen, Nanite, Ray tracing, 3D render", "Low"),
  l("183", "阿莱摄影机 (Arri Alexa)", "【电影工业质感】 模拟顶级电影摄影机的色彩科学（宽动态范围、柔和高光）。", "Shot on Arri Alexa, Log-C, Dynamic range, Cinematic look", "Low"),
  l("184", "柯达胶卷 (Kodak Portra)", "【复古/肤色优化】 模拟胶片的颗粒感和暖调色彩，对人物肤色表现极佳。", "Kodak Portra 400, Film grain, Warm tones, Analogue photography", "Low"),
  l("185", "16mm 胶片 (16mm Film)", "【独立电影/粗砺】 较粗的颗粒感，复古且带有文艺气息，适合回忆或独立电影风格。", "Super 16mm, Heavy grain, Vintage texture, Indie movie", "Low"),
  l("186", "VHS 录像带 (VHS Tape)", "【故障/80年代/恐怖】 模拟磁带的扫描线、色彩失真和低分辨率，制造年代感或不安感。", "VHS aesthetic, Tracking lines, Low resolution, Magnetic distortion", "Low"),
  l("187", "GoPro 运动视角 (Action Cam)", "【广角/畸变/极限】 模拟运动相机的超广角和深景深，用于第一人称的极限运动或动作戏。", "GoPro footage, Fisheye lens, High contrast, Sharp details", "Low"),
  l("188", "无人机航拍 (Drone Footage)", "【平滑/高空】 稳定的高空视角，用于大范围的场景展示。", "Drone shot, Aerial footage, Smooth gimbal, High altitude", "Low"),
  l("189", "热成像 (Thermal Imaging)", "【军事/特殊视觉】 模拟热感应色彩（红/蓝/黄），用于军事打击或非人类视角。", "Thermal imaging, Heat map, Predator vision", "Low"),
  l("190", "夜视仪 (Night Vision)", "【战术/潜行/绿色】 模拟夜视镜的绿色荧光和噪点，用于夜间作战或恐怖探索。", "Night vision goggles, Green phosphor, Grainy noise", "Low"),
  l("191", "微距摄影 (Macro Photo)", "【肉眼不可见】 极度贴近物体，展示纹理细节（如昆虫复眼、虹膜）。", "Macro photography, Microscopic detail, 100mm macro lens", "Low"),
  l("192", "电影颗粒 (Film Grain)", "【去除塑料感】 增加画面的噪点纹理，防止 AI 生成那种过于光滑、油腻的“塑料感”。", "Film grain, Noise overlay, Texture, Organic look", "Low"),
  l("193", "运动模糊 (Motion Blur)", "【速度感/真实】 模拟物体快速移动时的拖影。如果没有它，动作戏会像定格动画一样生硬。", "Motion blur, Speed streaks, Blurry movement, Shutter speed 1/50", "Low"),
  l("194", "色差故障 (Chromatic Aberration)", "【边缘真实感】 模拟镜头边缘的红蓝溢色。适度使用能增加画面的光学真实感，过度使用则产生故障风。", "Chromatic aberration, RGB shift, Lens defect", "Low"),
  l("195", "双重曝光 (Double Exposure)", "【艺术/心理投射】 将两个画面叠加（如人像轮廓内填充风景）。用于片头或表达人物复杂的内心。", "Double exposure, Image overlay, Silhouette filled with nature", "Low"),
  l("196", "延时摄影 (Time-Lapse)", "【时间压缩】 快速播放云彩流动、车流穿梭。用于表现时间的快速流逝。", "Time-lapse, Fast forward, Speeding clouds, Light trails", "Low"),
  l("197", "慢动作 (Slow Motion)", "【时间凝固/强调】 放慢动作细节。用于强调关键瞬间或营造唯美/悲伤的氛围。", "Slow motion, High frame rate, 120fps, Fluid motion", "Low"),
  l("198", "子弹时间 (Bullet Time)", "【全方位静止】 时间静止，摄影机移动。黑客帝国经典特效。", "Bullet time, Frozen time, Camera moving around static object", "Extreme"),
  l("199", "定格 (Freeze Frame)", "【瞬间暂停】 画面完全静止，用于介绍人物或作为结局。", "Freeze frame, Pause, Still image", "Low"),
  l("200", "无剪辑长镜头 (Continuous Shot)", "【连贯/沉浸】 强调画面没有剪辑点，一气呵成。", "One continuous shot, No cuts, Seamless", "High"),

  // Part 6: Genre: Action & Horror (201-240)
  l("201", "窄快门/频闪 (Skinny Shutter)", "【战争/焦虑/脆硬】 将快门角度设为 45 度或更低（如《拯救大兵瑞恩》）。消除运动模糊，使动作变得卡顿、脆硬，每一粒飞溅的泥土都清晰可见。极大增强战场的焦虑感和真实感。", "Skinny shutter, 45 degree shutter angle, Staccato motion, No motion blur, Crisp action, War movie style", "Low"),
  l("202", "战斗手持 (Combat Shaky Cam)", "【混乱/临场/冲击】 比普通手持更剧烈的高频震动。模拟摄影师在爆炸和枪林弹雨中奔跑的状态。用于表现战场混乱、甚至摄影机被冲击波击中的瞬间。", "Combat camera, Violent camera shake, High frequency jitter, Chaos, War zone footage", "Low"),
  l("203", "撞击震动 (Impact Tremor)", "【物理打击/力量感】 当重拳击中或重物落地时，摄影机瞬间剧烈震动一下。让观众在视觉上感受到“痛感”和力量的传导。", "Camera shake on impact, Impact tremor, Sudden jolt, Heavy hit", "Med"),
  l("204", "镜头飞溅 (Lens Debris)", "【打破第四面墙/沉浸】 泥土、血迹、水滴或火星飞溅到镜头玻璃上。打破“观众是旁观者”的安全感，暗示观众就在战场中心。", "Debris on lens, Blood splatter on camera, Rain drops on lens, Dirty lens, Immersive", "Low"),
  l("205", "枪口闪光照明 (Muzzle Flash Light)", "【频闪/瞬时高光/节奏】 黑暗环境中，仅靠枪口的闪光照亮人物面部。光影的极速明暗交替制造出强烈的视觉节奏和紧张感。", "Lit by muzzle flash, Strobe lighting from gun, Intermittent lighting, Darkness", "Med"),
  l("206", "动作对角线 (Dynamic Dutch)", "【动感/速度/失衡】 在动作戏中大幅度使用荷兰角（倾斜构图）。打破水平线的稳定性，让追逐和打斗看起来更快、更危险。", "Dutch angle action, Tilted horizon, Dynamic composition, Diagonal framing", "Low"),
  l("207", "低角度跟拍 (Low Angle Tracking)", "【脚步/紧迫/逃亡】 摄影机贴近地面，快速后退或跟随角色的脚步奔跑。强调逃亡的紧迫感和路面的障碍。", "Ground level tracking, Running feet, Fast moving floor, Chase scene", "Low"),
  l("208", "极速穿梭 (Velocity Pass)", "【速度感/模糊】 物体（车、子弹、人）极速掠过镜头，充满整个画面并瞬间消失。用于转场或强调速度之快。", "Object flying past camera, Fast motion blur, Whoosh effect, High speed pass", "Low"),
  l("209", "慢动作特写 (Impact Slow-Mo)", "【暴力美学/细节】 在击打接触的瞬间进入超级慢动作，展示肌肉的波纹、玻璃的碎裂或汗水的飞溅。", "Super slow motion, Impact freeze, Face distortion, Fluid mechanics, High frame rate", "Low"),
  l("210", "速度线 (Speed Lines)", "【漫画感/聚焦】 (AI模拟) 背景因极速移动而拉成线条状模糊，主体清晰。源自日漫的视觉语言，用于表现极速冲刺。", "Speed lines, Radial blur background, Anime action style, Fast focus", "Low"),
  l("211", "旋转跌落 (Tumble Cam)", "【失控/翻滚/晕眩】 模拟摄影机随角色一起滚下山坡或楼梯。天地旋转，画面极度混乱，表现彻底的失控。", "Tumbling camera, Rolling down hill, Spinning view, Chaos", "High"),
  l("212", "弹道视角 (Projectile POV)", "【致命/精确/奇观】 摄影机“骑”在子弹、箭矢或飞刀上。以第一人称视角飞向目标。极具视觉冲击力的奇观镜头。", "Bullet POV, Arrow camera, Projectile view, Flying towards target", "Med"),
  l("213", "背光剪影打斗 (Silhouette Fight)", "【形式感/武侠/简洁】 在强逆光（如月光、火光）下，动作简化为黑色的剪影。强调肢体的线条美和动作的清晰度，去除血腥细节。", "Silhouette fighting, Action against bright background, Shadow combat, Kill Bill style", "Low"),
  l("214", "双雄背靠背 (Back to Back Orbit)", "【合作/被围/绝境】 两个主角背靠背站立，摄影机环绕拍摄。经典的伙伴动作片镜头，暗示他们四面楚歌，只能互为后盾。", "Back to back characters, 360 orbit, Surrounded by enemies, Partner action", "Med"),
  l("215", "英雄落地 (Superhero Landing)", "【登场/力量/定格】 角色高空跳下，单膝跪地，地面碎裂，尘土飞扬。摄影机配合轻微震动。标准的主角登场镜头。", "Superhero landing, Three point landing, Ground crack, Dust shockwave, Epic pose", "Low"),
  l("216", "负片补光 (Negative Fill)", "【吞噬/阴暗/绝望】 并非打光，而是用黑布吸收光线，增加阴影的浓度。使画面的暗部死黑一片，仿佛黑暗在吞噬角色。", "Negative fill, Deep black shadows, Light absorption, High contrast darkness", "Low"),
  l("217", "视觉遮挡 (Visual Obstruction)", "【偷窥/不安/未知】 在前景放置大量遮挡物（树枝、家具、墙角），只露出主体的一部分。让观众感觉像是一个潜伏的猎手在窥视猎物。", "Obstructed view, Peeking through clutter, Hiding behind object, Voyeuristic", "Med"),
  l("218", "门缝推轨 (Doorway Dolly)", "【缓慢逼近/恐惧】 摄影机极其缓慢地推向一扇半开的门或黑暗的走廊尽头。利用观众对未知的想象力制造恐惧。", "Slow dolly towards door, Creeping camera, Dark corridor, Anticipation", "Low"),
  l("219", "锁孔视角 (Keyhole View)", "【限制/秘密/极度偷窥】 视线被限制在一个钥匙孔状的黑色遮罩内。极窄的视野迫使观众拼命想看清里面的内容，增加心理压力。", "Keyhole view, Vignette shape, Limited vision, Peeping", "Low"),
  l("220", "镜面反射 (Mirror Reveal)", "【虚实/惊吓/双重人格】 利用镜子拍摄角色。常用于“打开镜柜门，关上时背后出现鬼”的经典惊吓（Jump Scare），或表现角色的精神分裂。", "Mirror reflection, Looking in mirror, Reflection reveal, Double image", "Med"),
  l("221", "身后留白 (Behind the Back Space)", "【心理暗示/危险】 在构图时，故意在角色身后留出大片的黑暗空间（违反常规构图）。观众会本能地觉得那里会钻出什么东西。", "Dead space behind character, Off-center framing, Uncomfortable composition", "Low"),
  l("222", "手电筒光束 (Flashlight Beam)", "【狭窄视野/探索】 画面全黑，只有一束晃动的手电光照亮局部。观众只能看到光圈里的东西，极大地限制了信息量，增加惊悚感。", "Lit by flashlight, Single beam of light, Darkness, Searching", "Low"),
  l("223", "杀手视角 (Killer POV)", "【呼吸感/跟踪/恶意】 模拟潜伏者的主观视角（带有沉重的呼吸声或手持晃动），在树丛或窗外盯着受害者。", "Killer's point of view, Stalking camera, Heavy breathing style, Watching from bushes", "Low"),
  l("224", "J-Horror 湿气 (Damp Texture)", "【阴冷/日式恐怖/腐烂】 强调环境的潮湿、发霉、滴水。模拟《午夜凶铃》等日式恐怖片的生理不适感。", "Damp texture, Wet walls, Mold, Cold sweat, Japanese horror style", "Low"),
  l("225", "影子怪物 (Expressionist Shadow)", "【暗示/表现主义】 只拍摄怪物的影子投射在墙上，且影子比实体巨大、扭曲。利用德国表现主义手法，让恐惧存在于想象中。", "Giant shadow on wall, Distorted silhouette, German expressionism, Nosferatu style", "Low"),
  l("226", "低头垂发 (The Grudge Look)", "【遮挡面部/恐怖谷】 长发遮住面部，只露出一只眼睛或完全看不见脸。利用人类对无法识别面孔的本能恐惧。", "Hair covering face, Sadako style, Creepy, Uncanny valley", "Low"),
  l("227", "诡异微笑 (The Creepy Smile)", "【反常/精神污染】 角色（通常是背景路人）面带僵硬、过分夸张的微笑直视镜头。制造恐怖谷效应。", "Uncanny smile, Wide grin, Staring directly at camera, Disturbing", "Low"),
  l("228", "突然回头 (Sudden Turn)", "【惊吓/打破预期】 角色缓慢移动，然后极其突然、反物理速度地回头。配合音效制造惊吓。", "Sudden head turn, Unnatural movement, Snap turn, Jump scare setup", "Med"),
  l("229", "角落凝视 (Corner Stare)", "【监控感/被动】 摄影机放置在天花板角落（高角度），拍摄角色在房间里的一举一动。像是一个恶灵在天花板上看着。", "High corner shot, Ceiling camera, Paranormal Activity style, Watching from above", "Low"),
  l("230", "无法解释的微动 (Subtle Movement)", "【细思极恐/背景】 画面前景是主角在做日常事，后景的门把手或椅子极其轻微地动了一下。不仔细看看不到，看到了就头皮发麻。", "Subtle background movement, Door handle turning, Object moving slightly, Unnoticed details", "Med"),
  l("231", "肢体扭曲 (Body Horror)", "【生理不适/变异】 强调骨骼错位、皮肤下的蠕动或非自然的关节弯曲。用于表现附身、变异或怪形。", "Body horror, Contorted limbs, Skin bulging, Unnatural posture, Cronenberg style", "High"),
  l("232", "红光洗礼 (Red Wash)", "【警报/危险/地狱】 整个场景被红色警报灯或血光笼罩。代表极度危险、杀戮开始或进入地狱维度。", "Red emergency lighting, All red scene, Alarm light, Danger", "Low"),
  l("233", "幽灵重影 (Ghosting/Smear)", "【超自然/灵体】 角色移动时留下半透明的拖影。用于表现灵魂出窍、幽灵移动或时间错乱。", "Motion trails, Ghosting effect, Long exposure smear, Supernatural", "Med"),
  l("234", "眼球特写 (Eye Panic)", "【极端恐惧/反射】 极特写拍摄恐惧的眼睛，瞳孔剧烈收缩，眼球快速转动，或在虹膜上反射出怪物的倒影。", "Extreme close-up eye, Dilated pupils, Reflection of monster, Panic", "Low"),
  l("235", "打破第四面墙 (Breaking the Wall)", "【挑衅/元恐怖】 角色或怪物直接贴近镜头，敲打玻璃，甚至似乎要穿过屏幕抓住观众。", "Talking to camera, Touching lens, Breaking fourth wall, Immersive horror", "Med"),
  l("236", "声音可视化 (Sound Wave)", "【寂静之地/听觉恐怖】 (AI隐喻) 用震动的尘埃、水面的波纹来表现声音的传播。用于“不能出声”的设定，强调死寂中的微小响动。", "Vibrating water, Dust motes dancing, Visualizing sound, Tension", "Low"),
  l("237", "无限回廊 (Infinite Hallway)", "【心理死循环/困境】 利用推轨变焦或镜子，创造出没有尽头的走廊。表现角色永远跑不出去的绝望。", "Infinite corridor, Repeating hallway, Looping space, Nightmare", "Low"),
  l("238", "突然熄灯 (Lights Out)", "【节奏/逼近】 灯光一盏盏熄灭，黑暗向角色逼近；或者开关灯的瞬间，怪物位置发生变化。", "Lights turning off one by one, Flickering darkness, Approaching shadow", "Low"),
  l("239", "床底视角 (Under Bed)", "【童年阴影/弱势】 摄影机在床底向外看，看到一双脚走来；或从外向床底看，看到一双发光的眼睛。", "View from under bed, Looking into darkness, Childhood fear", "Low"),
  l("240", "伪安全感 (False Safety)", "【反转/阳光下的恐怖】 画面明亮、温馨、音乐柔和，但在背景或角落里出现极其恐怖的元素（如窗外的人脸）。对比度制造更深的恐惧。", "Bright horror, Daylight horror, Creepy detail in sunny scene, Midsommar style", "Med"),

  // Part 7: Sci-Fi & Surrealism (241-280)
  l("241", "全息界面主观 (HUD POV)", "【信息交互/钢铁侠视角】 模拟角色透过高科技头盔或眼镜看到的画面。叠加数据、锁定框、生物体征等 UI 元素。用于表现机甲驾驶员或未来战士的视角。", "HUD POV, Heads-up display, Iron Man interface, Data overlay, Target locking, Blue digital text", "Low"),
  l("242", "激光雷达扫描 (Lidar Scan)", "【探索/甚至AI视觉】 黑暗环境被一道道激光扫描线照亮，显示出物体的三维网格轮廓。用于表现机器人、无人机或特种部队在未知区域的探测。", "Lidar scan visualization, Laser mapping, 3D point cloud, Grid scanning effect, Dark environment", "Med"),
  l("243", "透视/剖面 (X-Ray Cutaway)", "【结构展示/精密】 摄影机仿佛拥有穿透力，透过外壳看到机器内部的齿轮运转，或人体内的骨骼/植入体。用于展示黑科技的精密结构或赛博义体。", "X-ray view, Cutaway diagram style, Internal mechanism, See-through machinery, Detailed gears", "Low"),
  l("244", "纳米变形 (Nanotech Morph)", "【流体金属/无缝重组】 物体或盔甲像液体一样流动、分解再重组。类似《终结者2》T-1000 或《复联》纳米战甲。展现极高的科技水平。", "Nanotech morphing, Liquid metal, Shape shifting, Flowing particles, Reassembling", "Med"),
  l("245", "曲速穿梭 (Warp Speed)", "【星际旅行/极速】 星星被拉成光线，瞬间向后飞逝。经典的太空旅行视觉符号，用于表现超光速航行或时间跳跃。", "Warp speed, Hyperspace jump, Star streaks, Light speed tunnel, Motion blur", "Low"),
  l("246", "零重力漂浮 (Zero-G Float)", "【太空/失重/优雅】 物体（水珠、笔、人）在空中自由悬浮、缓慢旋转。表现太空环境的静谧与优雅，或飞机俯冲时的失重瞬间。", "Zero gravity, Floating objects, Water droplets floating, Slow rotation, Weightlessness", "Low"),
  l("247", "头盔反射 (Helmet Reflection)", "【孤独/宇宙/目击】 极特写拍摄宇航员的头盔面罩，通过面罩上的倒影来展示他所看到的壮观景象（如地球升起、爆炸）。极具电影感的间接叙事。", "Reflection in astronaut helmet, Visor reflection, Face inside helmet, Space background", "Low"),
  l("248", "巨行星压顶 (Planetary Rise)", "【巨物恐惧/异星】 在地平线上方，一颗巨大的行星或月亮占据了半个天空。极具视觉压迫感，立即确立“这是外星”的世界观。", "Giant planet in sky, Massive moon on horizon, Alien landscape, Megastructure sky", "Low"),
  l("249", "太空对接 (Space Docking)", "【旋转匹配/工业美学】 两个巨大的物体在太空中缓慢、精准地同步旋转并连接。模仿《星际穿越》，配合圆舞曲般的节奏，展现工业机械之美。", "Space station docking, Matching rotation, Slow approach, Spacecraft mechanism", "Med"),
  l("250", "黑洞引力透镜 (Black Hole Lensing)", "【物理奇观/吞噬】 模拟黑洞周围的光线扭曲（吸积盘）。背景星空呈现环状变形。用于表现终极的宇宙力量或毁灭的边缘。", "Black hole accretion disk, Gravitational lensing, Light bending, Interstellar style, Event horizon", "Low"),
  l("251", "微缩宇宙 (Microverse)", "【量子领域/无限缩小】 摄影机不断推入物体的纹理，直到进入原子层面，发现里面包含着另一个宇宙。用于表现量子领域或微观世界的奇观。", "Microverse, Quantum realm, Subatomic particles, Fractal patterns, Infinite zoom in", "High"),
  l("252", "赛博义眼 (Cybernetic Eye)", "【特写/非人/数据流】 特写拍摄角色的眼球，发现虹膜是机械光圈，或瞳孔中有数据流过。暗示角色是仿生人或经过改造。", "Cybernetic eye close-up, Robotic iris, Glowing pupil, Data stream in eye", "Low"),
  l("253", "全息投影会议 (Hologram Meeting)", "【科幻通讯/幽灵感】 角色以半透明、带扫描线的全息影像形式出现。可以随时消失或受到干扰闪烁。", "Hologram figure, Blue transparent projection, Scanlines, Glitchy transmission", "Low"),
  l("254", "轨道电梯 (Space Elevator)", "【宏大/垂直/连接】 摄影机沿着一根通天的缆绳垂直向上飞升，穿过云层，直达太空。表现人类工程学的极致奇迹。", "Space elevator, Vertical cable to sky, Camera rising through clouds, Megastructure", "Low"),
  l("255", "故障艺术 (Datamosh/Glitch)", "【被黑/虚拟现实/崩塌】 画面出现像素拉伸、色彩分离、块状马赛克。用于表现模拟程序出错、系统被黑客攻击或记忆被篡改。", "Datamosh, Glitch art, Pixel sorting, System error visual, Digital corruption", "Low"),
  l("256", "空间折叠 (Inception Fold)", "【城市弯曲/物理崩塌】 整个城市或地面向上卷起，形成一个封闭的盒子状空间。源自《盗梦空间》，用于表现梦境或现实扭曲。", "City folding up, Inception style, Bending horizon, Defying physics, Surreal architecture", "High"),
  l("257", "无限循环/德罗斯特 (Droste Effect)", "【死循环/深渊】 画面中心包含一个缩小的自己，无限套娃。或者角色打开门，发现门后还是同一个房间。用于表现心理困境或时间循环。", "Droste effect, Infinite recursion, Picture within picture, Looping corridor, Fractal", "Med"),
  l("258", "融化现实 (Melting Reality)", "【达利风格/时间崩塌/高温】 场景中的物体（钟表、墙壁、脸）像蜡一样融化流淌。用于表现超现实梦境、极度高温或药物幻觉。", "Melting objects, Dali style, Dripping clock, Liquid walls, Surrealism", "Med"),
  l("259", "非欧几何空间 (Non-Euclidean)", "【迷宫/错觉/困惑】 利用视觉错觉（如埃舍尔阶梯），让角色走上楼梯却回到了起点，或在天花板上行走。表现逻辑的彻底失效。", "Escher stairs, Impossible geometry, Non-euclidean space, Optical illusion", "High"),
  l("260", "浮空岛屿 (Floating Islands)", "【奇幻/阿凡达/仙境】 巨大的岩石或岛屿漂浮在空中，有瀑布流下。构建一个反重力的奇幻世界观。", "Floating islands, Avatar style, Anti-gravity rocks, Waterfalls in sky, Fantasy landscape", "Low"),
  l("261", "镜面维度 (Mirror Dimension)", "【万花筒/魔法/奇异博士】 空间像镜子碎片一样分裂、折射、复制。世界变成无数个切面。用于表现魔法战斗或维度穿越。", "Mirror dimension, Fractured reality, Kaleidoscope world, Shattered glass effect", "High"),
  l("262", "物体巨大化 (Gigantism)", "【荒诞/爱丽丝/压迫】 日常物品（如椅子、茶杯、猫）变得如高楼般巨大。用于《爱丽丝梦游仙境》式的荒诞感，或突显角色的渺小。", "Giant everyday object, Alice in Wonderland style, Massive scale contrast, Surreal", "Low"),
  l("263", "隐形人轮廓 (Invisible Silhouette)", "【雨中/尘埃/惊悚】 角色是隐形的，但通过雨水、烟雾或身上的油漆勾勒出轮廓。用于表现隐形生物的存在。", "Invisible man outline, Rain hitting invisible shape, Dust silhouette, Ghostly figure", "Med"),
  l("264", "分身拖影 (Clone Trail)", "【速度/时间残像/多重人格】 角色移动时，身后留下一串静止的实体分身。用于表现超光速移动，或者角色在不同时间点的状态同时存在。", "Motion trail of clones, Multiple exposures, Echo effect, Time remnant", "Med"),
  l("265", "面部变形 (Face Morph)", "【伪装/恐怖/身份流动】 角色的五官像液体一样流动，变成另一个人的脸。用于表现外星人伪装、AI 换脸或自我认知的丧失。", "Face morphing, Changing features, Liquid face, Identity shift", "Med"),
  l("266", "天空之眼 (Eye in the Sky)", "【审判/神/老大哥】 天空中不是太阳，而是一只巨大的眼睛在俯视大地。极具压迫感，暗示被神明或极权监视。", "Giant eye in the sky, Surrealism, Watching world, Cosmic horror", "Low"),
  l("267", "时间倒流 (Time Reversal)", "【因果逆转/复原】 破碎的玻璃飞回重圆，泼出的水回到杯中，烟雾回到烟囱。用于表现时间控制能力或熵减。", "Reverse motion, Shattered glass fixing itself, Time flowing backwards, Entropy reversal", "Low"),
  l("268", "水下呼吸 (Underwater Gravity)", "【梦境/唯美/窒息】 角色在正常的房间里，但头发和衣服像在水下一样漂浮，或者房间里充满了水。表现潜意识深处的情绪。", "Underwater physics in room, Floating hair, Submerged room, Dreamlike", "Low"),
  l("269", "传送门开启 (Portal Opening)", "【穿越/连接/奇异博士】 空间中撕裂出一个发光的圆环或裂缝，透过它看到完全不同的风景。", "Magic portal, Dimensional rift, Glowing ring, View to another world", "Low"),
  l("270", "人体悬浮 (Levitation)", "【超能力/附身/升天】 角色双脚离地，违反重力地悬浮在半空。用于表现超能力觉醒、被恶魔附身或宗教性的升天。", "Human levitation, Floating person, Feet off ground, Supernatural power", "Low"),
  l("271", "无限缩放 (Infinite Zoom)", "【分形/迷幻/晕眩】 摄影机不断地推入画面的中心，画面中心又是这一画面的重复。形成一种永无止境的视觉隧道。", "Infinite zoom loop, Fractal zoom, Never ending tunnel, Psychedelic", "High"),
  l("272", "石化崩塌 (Petrification)", "【毁灭/时间静止/雕像】 角色或物体瞬间变成石头，然后崩裂成碎块。用于表现美杜莎的能力或生命的瞬间终结。", "Turning to stone, Petrification, Cracking statue, Crumbling", "Med"),
  l("273", "云端漫步 (Walking on Clouds)", "【天堂/自由/超现实】 角色直接行走在云层之上，如同行走在平地。用于表现天堂、梦境或极度的自由感。", "Walking on clouds, Sky floor, Above the clouds, Surreal landscape", "Low"),
  l("274", "纸片人 (Paper Cutout)", "【二维化/脆弱/怪诞】 三维的角色突然变成一张二维的纸片飘落，或像书页一样翻开。表现维度的降级或现实的虚假。", "Paper cutout style, 2D character in 3D world, Flat stanley, Surreal transformation", "Med"),
  l("275", "发光血管 (Glowing Veins)", "【变异/能量过载/感染】 皮肤下透出岩浆般或蓝色的发光血管网络。用于表现病毒感染、能量注入或即将自爆。", "Glowing veins under skin, Lava skin, Energy surge, Body transformation", "Low"),
  l("276", "多重曝光剪影 (Double Exposure Silhouette)", "【真探风格/内心投射】 画面是角色的黑色剪影，但剪影内部填充的是汹涌的海浪或燃烧的森林。表现角色内心的风暴。", "Double exposure silhouette, Ocean inside body, True Detective intro style", "Low"),
  l("277", "像素化消散 (Pixel Disintegration)", "【数字化/删除/灭霸】 角色像被数据删除一样，分解成无数个像素方块飘散。表现数字生命的死亡或系统的崩溃。", "Pixel disintegration, Dissolving into pixels, Thanos snap digital style", "Low"),
  l("278", "镜面地面 (Reflective Floor)", "【无限空间/纯净/死后】 角色站在无边无际的平静水面或镜面上，倒影清晰。用于表现死后的世界（如《千与千寻》列车）或内心空间。", "Infinite reflective floor, Water surface, Perfect reflection, Void space", "Low"),
  l("279", "身体分裂 (Body Split)", "【甚至恐怖/解剖】 身体像切片面包一样分开，中间没有血肉而是机械结构或虚空。极具视觉冲击力的超现实画面。", "Sectioned body, Sliced anatomy, Surreal cross section, Magical split", "High"),
  l("280", "文字实体化 (Text Materialization)", "【设计感/MV/片头】 巨大的3D文字悬浮在空中，与角色产生互动（如角色坐在字母上）。用于片头设计或极具风格化的MV。", "Giant 3D text in scene, Typography interacting with environment, Kinetic type", "Low"),

  // Part 8: Advanced Blocking (281-320)
  l("281", "动机跟随 (Motivated Camera)", "【最基础/自然】 只有当角色移动时，摄影机才移动；角色停，摄影机停。这种调度让运镜完全隐形，观众感觉不到摄影机的存在，只关注剧情。", "Motivated camera movement, Camera follows subject action, Starts and stops with character, Natural blocking", "Low"),
  l("282", "反向揭示 (Counter-Move Reveal)", "【惊喜/信息量】 角色向左走，摄影机却向右移动（反向），利用视差在角色身后揭示出原本被遮挡的关键信息（如身后的杀手、远处的爆炸）。", "Camera moves opposite to subject, Reveal from behind character, Counter movement blocking, Parallax reveal", "Med"),
  l("283", "起立特写 (Stand and Deliver)", "【权威/压迫/宣判】 角色从坐姿突然站起，摄影机不后退，而是让角色直接逼近镜头成为大特写。表现角色的愤怒、夺取控制权或施加极大的心理压力。", "Character stands up into close-up, Looming over camera, Power move, Dominant blocking", "Low"),
  l("284", "交替过肩 (The Cross)", "【权力转移/对峙】 两人对话时，角色 A 突然走到角色 B 身后或侧面，摄影机随之移动，改变了背景和两人的站位关系。表现对话中话语权的转移或局势变化。", "Character crossing frame, Changing sides, Blocking change, Shifting power dynamic", "Med"),
  l("285", "摩西分海 (Crowd Parting)", "【焦点/孤独/逆行】 主角逆着人流方向行走，人群自动向两边分开；或者主角站定，人群绕过他流动。表现主角的决绝、孤独或与世界的格格不入。", "Walking against crowd, Crowd parting, Subject stationary crowd moving, Moses effect", "High"),
  l("286", "边走边谈 (The Walk and Talk)", "【索金式/节奏/信息量】 多个角色并排或前后快速行走，摄影机后退跟拍，边走边进行高密度的对话。用于交代大量信息同时保持画面的动态节奏。", "Walk and talk, Tracking shot backwards, Group walking fast, Sorkin style, Busy corridor", "Med"),
  l("287", "聚合圆阵 (The Huddle)", "【密谋/团结/甚至霸凌】 多个角色围成一圈低头看镜头（摄影机在下），或摄影机围绕聚在一起的一群人。用于战前动员、制定犯罪计划或校园霸凌视角。", "Circular huddle, Low angle looking up at group, Heads together, Team planning", "Low"),
  l("288", "背景现身 (Background Reveal)", "【惊悚/伏笔】 前景角色向侧面移动一步，露出原本被他身体挡在后景的另一个人（或怪物）。利用身体作为遮挡物的经典惊吓调度。", "Character steps aside to reveal, Reveal from behind body, Background surprise, Blocking reveal", "Med"),
  l("289", "焦点接力 (The Hand-Off)", "【长镜头/视点转换】 摄影机跟随角色 A，直到 A 遇到角色 B，摄影机抛弃 A，开始跟随 B。用于在长镜头中自然地转换叙事视角，连接不同的人物线。", "Camera switches subjects, Following new character, Narrative hand-off, Continuous shot", "High"),
  l("290", "德州切换 (Texas Switch)", "【AI特技/变身】 (AI模拟) 角色跑过一根柱子或遮挡物，瞬间变成另一个人（或怪物/替身）。在传统电影中是特技替身技巧，在 AI 中用于表现变身或时空错乱。", "Texas switch, Character swap behind object, Seamless transformation, Match cut", "High"),
  l("291", "镜面博弈 (Mirror Blocking)", "【自我审视/双重人格】 角色对着镜子说话，摄影机在现实和镜中倒影之间来回切换焦点。表现角色的自我怀疑、疯狂或分裂。", "Acting to mirror, Focus pull to reflection, Talking to self, Split personality", "Low"),
  l("292", "前景穿梭 (Foreground Wipe)", "【转场/甚至偷袭】 路人、服务员或车辆从极近的前景快速穿过，瞬间遮挡画面。可用作无缝转场点，或在穿过后场景发生突变（如人突然消失）。", "Foreground wipe, Person walking past lens, Transition masking, Sudden change", "Low"),
  l("293", "三角站位 (Triangular Staging)", "【墨西哥对峙/张力】 三个角色呈三角形站位，互相牵制。摄影机在其中穿梭，展示复杂的视线关系。常用于枪战前的僵局或情感修罗场。", "Triangular composition, Three way standoff, Mexican standoff, Deep focus blocking", "Med"),
  l("294", "嫌疑人列队 (The Line-Up)", "【群像/对比/挑选】 多个角色并排站立面对镜头（如《通常嫌疑犯》）。用于展示团队成员的差异、挑选凶手或英雄集结。", "Character line-up, Standing side by side, Team assembly, Police lineup", "Low"),
  l("295", "四散奔逃 (The Scatter)", "**【恐慌/甚至爆炸】**原本聚集的人群突然向四面八方炸开式奔跑。用于表现爆炸前一秒、突发枪击或怪兽从中心破土而出。", "Crowd scattering, Running in all directions, Explosion reaction, Panic dispersal", "High"),
  l("296", "中心汇聚 (The Converge)", "【决战/压迫】 四面八方的敌人慢慢向画面中心的英雄逼近。制造极强的窒息感和包围感。", "Enemies circling in, Converging on center, Surrounded, Closing the gap", "Med"),
  l("297", "走入特写 (Walk into Close-Up)", "【强调/顿悟】 角色从远景直接走到镜头极近处停下，脸部填满画面。用于表现角色下定决心、发现真相或向观众（打破第四面墙）传递情绪。", "Walking from wide to close-up, Approaching camera, Face filling frame, Intense realization", "Low"),
  l("298", "转身背离 (The Turn Away)", "【拒绝/结束/甚至背叛】 角色在特写中突然转身背对镜头，走向深处。标志着一场对话的决裂、一个时代的结束或角色的黑化。", "Turning back on camera, Walking away into distance, Rejection, End of scene", "Low"),
  l("299", "回眸 (The Look Back)", "【留恋/甚至惊鸿一瞥】 角色走向远方，停步，回头看一眼镜头。经典的情感调度，用于告别、犹豫或悬疑片中的“最后一眼”。", "Looking back over shoulder, Stopping to look back, Hesitation, Farewell", "Low"),
  l("300", "坠落跟随 (The Fall Away)", "【无助/死亡/深渊】 角色向后倒下（坠楼/坠崖），摄影机在崖边俯视，看着他越来越小直至消失。表现彻底的无助和命运的终结。", "Falling away from camera, Dwindling figure, Falling into void, Top down view", "Med"),
  l("301", "狭路相逢 (Corridor Squeeze)", "【冲突/暧昧/甚至打斗】 两个角色在狭窄的走廊中擦肩而过，身体几乎接触。表现强烈的性张力、敌意或一触即发的打斗。", "Passing in narrow hallway, Close proximity, Shoulder check, Tension", "Low"),
  l("302", "电梯门缝 (Elevator Closing)", "【隔离/绝望/秘密】 透过正在关闭的电梯门缝拍摄内部的角色。随着缝隙变窄，角色的表情被切断。用于表现无法触及的距离或最后一眼的秘密。", "Elevator doors closing, View through gap, Disappearing character, Isolation", "Low"),
  l("303", "窗户触摸 (Window Touch)", "【渴望/囚禁/隔离】 角色把手按在玻璃上，凝视窗外。摄影机在窗外拍摄，叠加了玻璃的反光。表现角色的囚禁感或对外界的渴望。", "Hand on glass, Looking out window, Reflection overlay, Longing", "Low"),
  l("304", "桌底视角 (Under Table)", "【隐秘/紧张/甚至调情】 摄影机放在桌子底下。可以看到紧张抖动的腿、秘密传递物品的手，或脚下的调情动作。", "View from under table, Feet shuffling, Secret exchange, Hidden action", "Low"),
  l("305", "车窗交互 (Car Window Exchange)", "【交易/离别/甚至暗杀】 一人在车内，一人在车外，通过摇下的车窗互动。经典的毒品交易、警察临检或依依惜别的调度位置。", "Framing through car window, Inside outside dynamic, Conversation framing", "Low"),
  l("306", "旋转展示 (The Reveal Turn)", "【身份揭露/甚至反派】 椅子背对镜头，慢慢转过来，露出坐在椅子上的人（通常抱着猫）。经典的反派登场调度。", "Chair swiveling around, Reveal villain, Slow turn to camera, Dramatic reveal", "Low"),
  l("307", "物品接力 (The Catch)", "【动感/精准】 画外抛入一个物体（钥匙、枪、啤酒），角色伸手稳稳接住。展示角色的反应速度和帅气程度。", "Catching object, Flying prop, Hand grab close-up, Reflex action", "Med"),
  l("308", "影子互动 (Shadow Play)", "【隐喻/甚至谋杀】 摄影机只拍摄墙上的影子，不拍实体。通过影子的动作（如举刀、亲吻）来表现剧情。含蓄而充满张力。", "Shadows on wall, Action via silhouette, Visual metaphor, No actors visible", "Low"),
  l("309", "人群逆流 (Against the Flow)", "【迷茫/时间停滞】 周围的人群都在快速前进，只有主角一人逆向缓慢行走或站立不动。表现主角与周围世界的脱节或内心的迷茫。", "Walking against traffic, Slow motion subject fast crowd, Isolation in crowd", "Med"),
  l("310", "视线引导 (Eyeline Guide)", "【隐形剪辑】 角色A看向右边 -> 摄影机向右摇 -> 看到角色B。利用角色的视线作为摄影机运动的动机。", "Pan following eyeline, Looking then revealing, Motivated pan", "Low"),
  l("311", "同框不视 (Shared Frame Ignorance)", "【错过/甚至悬疑】 杀手和受害者在同一个宽景别画面中，但中间隔着一堵墙或背对背，互相没看见。观众拥有全知视角，产生焦急感。", "Split screen effect naturally, Unaware of each other, Shared space, Suspense", "Med"),
  l("312", "前景压迫 (Foreground Looming)", "【威胁/甚至审讯】 一个模糊的巨大背影（如警察/黑帮）占据前景大部分，主角在后景显得很小。表现权力的极度不对等。", "Looming shoulder foreground, Dominant silhouette, Small subject background", "Low"),
  l("313", "对称构图破局 (Breaking Symmetry)", "【打破秩序/甚至反叛】 画面原本是完美的对称（如阅兵），突然一个人走出队列，破坏了平衡。表现觉醒、反叛或秩序的崩溃。", "Breaking formation, Disrupting symmetry, One person moving, Rebellion", "Low"),
  l("314", "极速对冲 (The Clash)", "【决战/冲击】 双方人马从画面左右两边极速冲向中心，最后撞在一起。史诗级战争场面的标准调度。", "Armies running at each other, Clash in center, High speed impact, Battle charge", "High"),
  l("315", "原地转圈 (The Dizzy Spin)", "【迷失/崩溃】 角色在原地转圈观察四周，摄影机跟着他转。表现角色的无助、找不到方向或被包围时的恐慌。", "Character spinning around, Camera spinning with subject, Panic looking, Disorientation", "Med"),
  l("316", "水平层级 (Level Hierarchy)", "【地位/阶级】 利用楼梯、阳台等结构。有权势的人站在高处俯视，无权势的人站在低处仰视。通过物理高度表现社会地位。", "High and low levels, Looking down from balcony, Staircase blocking, Status difference", "Low"),
  l("317", "光区移动 (Stepping into Light)", "【真相/坦白/甚至登场】 角色从完全的黑暗中一步步走到聚光灯下。表现角色决定暴露身份、坦白真相或从阴影中归来。", "Walking out of shadows, Emerging into light, Reveal, Dramatic entrance", "Low"),
  l("318", "退入黑暗 (Fading into Black)", "【消失/死亡/甚至绝望】 角色慢慢后退，直到被身后的黑暗完全吞没。表现角色的死亡、被遗忘或主动选择堕落。", "Backing into darkness, Disappearing in shadow, Fade to black, Ominous exit", "Low"),
  l("319", "物体传递 (Prop Relay)", "【连接/长镜头】 镜头跟随物品（如一封信、一包毒品）在不同人手中传递。通过物品的动线串联起整个场景的人物关系。", "Following object, Passing prop hand to hand, Relay shot, Connection", "Med"),
  l("320", "打破第四面墙 (The 4th Wall Break)", "【挑衅/甚至元叙事】 角色突然停止剧情，转头直视镜头，甚至对观众说话（《纸牌屋》、《死侍》）。打破虚构的界限。", "Looking directly at camera, Talking to audience, Breaking fourth wall, Meta", "Low"),

  // Part 9: Transitions & Editing (321-360)
  l("321", "图形匹配 (Graphic Match)", "【经典/诗意/轮回】 镜头A的结尾物体（如圆形的排水口）在形状上与镜头B的开头物体（如眼睛）完美重合。库布里克《2001太空漫游》骨头变飞船的经典手法。", "Graphic match transition, Shape morphing, Bone to spaceship, Match cut circular object", "Med"),
  l("322", "动作匹配 (Match on Action)", "【流畅/动感/打斗】 镜头A：角色挥拳打向镜头；镜头B：反派被击中飞出。利用动作的连贯性连接两个不同时空的场景。", "Match on action, Continuous movement, Punch transition, Seamless action cut", "Low"),
  l("323", "极速甩镜 (Whip Pan Transition)", "【隐藏剪辑/快节奏】 镜头A在结尾处极速向右甩动（模糊）；镜头B从左侧极速甩入（模糊）并定格。利用动态模糊隐藏剪辑点。", "Whip pan right, Fast swish pan, Motion blur transition, Hidden cut", "High"),
  l("324", "遮挡转场 (Masking/Wipe)", "【自然/偷袭/时间流逝】 角色或物体（如柱子、背影）走到镜头极近处，完全遮挡画面变黑。当遮挡物移开时，背景已经变成了另一个场景。", "Foreground wipe, Object covering lens, Transition through black, Masking cut", "Low"),
  l("325", "瞳孔穿越 (Eye Zoom Transition)", "【宇宙/内心/连接】 摄影机无限推入角色的瞳孔，穿过黑色的虹膜，进入浩瀚宇宙或下一个场景。", "Zoom into eye pupil, Macro eye transition, Enter new world through eye, Universe in eye", "Med"),
  l("326", "屏幕穿越 (Screen Dive)", "【媒体/虚拟/矩阵】 摄影机推入电视、手机或电脑屏幕，直到屏幕边框消失，观众直接进入了屏幕里的世界。", "Zoom into TV screen, Pass through monitor, Pixel transition, Enter digital world", "Low"),
  l("327", "镜面穿越 (Mirror Through)", "【梦境/魔幻/爱丽丝】 摄影机直接穿过镜子表面，进入镜中世界。表现现实与虚幻的界限崩塌。", "Camera passing through mirror, Liquid glass surface, Entering reflection, Magical transition", "High"),
  l("328", "暗部转场 (Shadow Blend)", "【潜行/悬疑/无缝】 角色走进一片死黑的阴影中，隐没不见；紧接着从另一片阴影中走出，但这已经是另一个地点。", "Walk into darkness, Fade to black transition, Emerge from shadows, Invisible cut", "Low"),
  l("329", "亮部转场 (Light Leak/Flash)", "【回忆/神性/刺眼】 镜头对准强光源（太阳、闪光灯），画面过曝全白。白光消散后，显现出新的场景（通常是回忆或天堂）。", "White out transition, Lens flare washout, Flash transition, Fade from white", "Low"),
  l("330", "天空转场 (Sky Tilt)", "【时空跨越/连接】 镜头A：向上仰拍直到只看到天空；镜头B：从天空向下俯拍，揭示新的城市或风景。", "Tilt up to sky, Blue sky transition, Tilt down to new scene, Location change", "Low"),
  l("331", "地面转场 (Ground Tilt)", "【坠落/脚步/连接】 镜头A：向下俯拍直到只看到地面（草地/柏油路）；镜头B：从地面向上仰拍，展示新环境。", "Tilt down to ground, Floor transition, Tilt up from floor, Connecting locations", "Low"),
  l("332", "旋转匹配 (Rotation Match)", "【甚至晕眩/时光流逝】 镜头A：旋转的车轮；镜头B：旋转的电风扇（或唱片、洗衣机）。利用旋转的角速度匹配连接画面。", "Spinning match cut, Rotating wheel to fan, Circular motion transition, Time passing", "Med"),
  l("333", "AI变形 (Morph Cut)", "【生物科技/恐怖/顺滑】 AI 的看家本领。物体 A 直接流体般变形成为物体 B（如狼变人，枪变玫瑰）。不需要剪辑，是原本就在画面里发生的。", "Morphing transition, Object A transforming into B, Seamless morph, Liquid transformation", "Low"),
  l("334", "故障转场 (Glitch Transition)", "【赛博/系统错误/黑客】 画面出现数字信号故障、色块撕裂、马赛克，瞬间切换到下一帧。", "Glitch transition, Datamosh, Digital noise, Signal interruption, Cyberpunk cut", "Low"),
  l("335", "燃烧转场 (Film Burn)", "【复古/胶片/记忆】 画面像老胶片一样被烧穿，卷曲、发黄、烧成灰烬，露出底下的新画面。", "Film burn transition, Burning celluloid, Fire reveal, Vintage effect", "Med"),
  l("336", "墨水转场 (Ink Blot)", "【艺术/回忆/罗夏测试】 黑色的墨水滴入水中扩散，遮挡画面，随后墨水消散显示新画面。", "Ink blot transition, Ink in water, Rorschach reveal, Artistic dissolve", "Low"),
  l("337", "像素化 (Pixelation)", "【游戏/分辨率降低】 画面逐渐变成马赛克方块，分辨率越来越低，直到变成另一个像素化的场景，再变清晰。", "Pixelation transition, Low res to high res, 8-bit effect, Mosaic fade", "Low"),
  l("338", "冻结帧 (Freeze Frame)", "【强调/结局/旁白】 视频突然定格成一张照片。常用于介绍角色（配字幕）或电影的开放式结局。", "Freeze frame, Action pause, Still image, Narration background", "Low"),
  l("339", "跳切 (Jump Cut)", "【焦虑/时间碎片/法式新浪潮】 摄像机机位不变，只是剪掉了中间的一段时间。人物在画面中突然瞬移。表现焦虑、时间流逝或精神错乱。", "Jump cut, Time skip same angle, Jerky movement, Anxiety edit", "Low"),
  l("340", "叠化 (Cross Dissolve)", "【梦幻/柔和/回忆】 画面A慢慢变淡，画面B同时慢慢浮现。两者重叠在一起，像幽灵一样。用于表现漫长的时间流逝或温柔的回忆。", "Cross dissolve, Double exposure fade, Ghostly overlay, Slow transition", "Low"),
  l("341", "时间重映射 (Speed Ramp)", "【强调/节奏/卡点】 视频速度从极快突然变极慢，再变极快。用于动作卡点或强调某个瞬间。", "Speed ramp, Fast to slow motion, Time remapping, Action highlight", "High"),
  l("342", "倒放 (Reverse Motion)", "【奇观/复原/诺兰】 破碎的杯子飞回桌上复原，烟雾倒流回烟囱。表现时间逆转或超自然力量。", "Reverse motion, Unbreaking, Backwards time, Entropy reversal", "Low"),
  l("343", "完美循环 (Perfect Loop)", "【GIF/无限/迷幻】 视频的最后一帧和第一帧完全无缝衔接。用于制作表情包、动态壁纸或表现死循环噩梦。", "Perfect loop, Seamless loop, Infinite animation, GIF style", "Med"),
  l("344", "分屏 (Split Screen)", "【多线叙事/对比/电话】 屏幕被分割成两半或多块，同时展示不同地点的场景。常用于电话场景或展示杀手与受害者的同步行动。", "Split screen, Side by side view, Dual narrative, Phone call framing", "Med"),
  l("345", "画中画 (Picture in Picture)", "【新闻/反应/直播】 屏幕角落出现一个小框，显示另一个画面。用于新闻直播、监控室或网络主播视角。", "Picture in picture, News overlay, Reaction cam, Monitor view", "Low"),
  l("346", "隐形剪辑 (Invisible Cut)", "【长镜头/希区柯克】 利用一段全黑（穿过背影）或全白（看天空）的瞬间进行剪辑，让观众以为是一镜到底。", "Invisible cut, Hidden edit, Seamless disguise, Rope cut", "Med"),
  l("347", "声波转场 (Sound Wave)", "【音乐/节拍/震动】 画面随着低音震动而模糊或变形，利用这种震动切换场景。用于MV或强调巨大的声响。", "Sound wave distortion, Bass shake, Vibrating transition, Music video style", "Low"),
  l("348", "镜头除雾 (Defogging)", "【揭示/清晰/雨后】 镜头上原本布满雾气或水汽，被一只手擦去，或者自然消散，露出新的清晰场景。", "Wiping fog from glass, Defogging lens, Condensation clear, Reveal", "Low"),
  l("349", "水面出入 (Water Transition)", "【两个世界/窒息】 摄影机猛地扎入水中（进入闷响的水下世界），再冲出水面（进入另一个地点）。", "Camera diving underwater, Surfacing from water, Water splash transition", "Low"),
  l("350", "门扉穿越 (Doorway Transition)", "【哆啦A梦/连接】 打开一扇门，门外却不是走廊，而是海滩或宇宙。利用门框作为天然的硬切点。", "Opening door to new world, Magical doorway, Portal transition", "Low"),
  l("351", "变焦模糊 (Zoom Blur)", "【极速/穿越/星战】 画面四周向中心拉出极长的模糊线条，模拟超光速飞行的瞬间。", "Zoom blur, Hyperdrive effect, Radial blur, High speed warp", "Low"),
  l("352", "RGB分离 (RGB Split)", "【震动/混乱/故障】 画面的红绿蓝通道分离位移，产生重影。用于表现撞击、头痛或精神不稳定。", "RGB split, Chromatic aberration shake, Color separation, Dizzy", "Low"),
  l("353", "轮廓填充 (Silhouette Fill)", "【艺术/回忆/真探】 画面变为黑白剪影，新的彩色画面像水流一样填充进黑色的剪影轮廓中。", "Silhouette fill, Image inside outline, Double exposure style", "Med"),
  l("354", "撕纸效果 (Paper Tear)", "【定格动画/手工/粗砺】 画面像纸张一样被从中间撕开，露出底下的新画面。", "Paper tear transition, Ripped edges, Stop motion style, Collage", "Low"),
  l("355", "液体融化 (Liquid Melt)", "【恐怖/高温/超现实】 整个画面像蜡像一样融化流淌下来，变成一滩彩色液体，重组为新画面。", "Screen melting, Dripping paint, Liquid dissolve, Surreal", "Med"),
  l("356", "粒子消散 (Particle Disperse)", "【灭霸/消失/风沙】 画面主体分解成无数细小的沙尘或光点随风飘散。", "Disintegrating into particles, Sand dispersion, Thanos snap effect, Dust", "Low"),
  l("357", "聚焦转场 (Rack Focus Transition)", "【柔和/注意力转移】 镜头A完全失焦变模糊；镜头B从模糊中逐渐变清晰。利用模糊段进行无缝连接。", "Rack focus transition, Blur in blur out, Focus pull reveal", "Low"),
  l("358", "360翻转 (360 Flip)", "【VR/动感/极限】 整个画面极速翻转一圈（天地倒置再回正）。用于极限运动或极具冲击力的场景切换。", "Camera flip 360, Spin transition, Tumble, Disorienting", "High"),
  l("359", "镜头破碎 (Shatter)", "【冲击/打破幻象】 画面像玻璃一样被击碎，碎片飞溅，露出后面的新场景。", "Glass shattering effect, Screen crack, Broken reality, Impact", "Low"),
  l("360", "淡入淡出 (Fade In/Out)", "【开始/结束/昏迷】 画面逐渐变黑（Fade Out）或从黑变亮（Fade In）。最基础的电影语法，表示一段故事的开始或结束。", "Fade to black, Fade from black, Slow fade, Ending scene", "Low"),

  // Part 10: Metaphor (361-400)
  l("361", "窗上的雨痕 (Rain on Glass)", "【悲伤/隔绝/哭泣】 拍摄窗玻璃上的水流，背景模糊。模拟“流泪”的视觉通感，表现角色的悲伤或与外界的心理隔绝。", "Raindrops on window, Water streaming down glass, Blurry city background, Melancholy, Crying metaphor", "Low"),
  l("362", "枯萎的花 (Wilting Flower)", "【逝去/死亡/绝望】 延时摄影展示花朵枯萎、花瓣掉落。隐喻生命的流逝、爱情的终结或希望的破灭。", "Wilting flower, Dying rose, Petals falling, Time lapse decay, Symbol of death", "Low"),
  l("363", "破茧成蝶 (Breaking the Cocoon)", "【重生/觉醒/蜕变】 昆虫冲破茧壳，或者雏鸟破壳。隐喻角色突破心理障碍、获得新生或能力觉醒。", "Butterfly emerging from cocoon, Breaking shell, Metamorphosis, Rebirth, New life", "Low"),
  l("364", "空椅子 (The Empty Chair)", "【缺失/怀念/死亡】 构图中心放一把空椅子，或者餐桌上的一副空碗筷。强烈暗示某人的缺席或离世。", "Empty chair, Empty seat at table, Absence, Loss, Lonely composition", "Low"),
  l("365", "燃烧的桥 (Burning Bridge)", "【决裂/无路可退】 角色身后的桥梁或道路燃起大火。隐喻切断后路、关系的彻底破裂或不可挽回的决定。", "Burning bridge, Fire on bridge, No return, Severing ties, Destruction", "Low"),
  l("366", "沙漏流逝 (Hourglass Macro)", "【紧迫/倒计时/宿命】 特写沙漏中的沙子落下。隐喻时间的无情流逝、生命的倒计时或无可改变的宿命。", "Hourglass close-up, Sand falling, Time running out, Countdown, Fatalism", "Low"),
  l("367", "笼中鸟 (Bird in Cage)", "【囚禁/渴望/束缚】 拍摄鸟笼中的鸟，或鸟撞击笼子。隐喻角色被社会规则、婚姻或环境所囚禁。", "Bird in cage, Trapped bird, Looking through bars, Imprisonment", "Low"),
  l("368", "飞鸟离去 (Bird Flying Away)", "【自由/解脱/灵魂】 一群鸟突然飞向天空，远离镜头。隐喻灵魂的升华、获得自由或消息的传播。", "Birds flying away, Flock in sky, Freedom, Liberation, Ascension", "Low"),
  l("369", "提线木偶 (Marionette Strings)", "【被控/无力/阴谋】 角色手脚上隐约可见丝线，或上方有巨大的手在操控。隐喻角色是棋子，被命运或幕后黑手操纵。", "Marionette strings, Puppet on strings, Giant hand controlling, Manipulation", "Med"),
  l("370", "溺水感 (Drowning)", "【压抑/窒息/无助】 角色在深水中下沉，伸手向上抓，光线越来越暗。隐喻生活压力的重负或心理崩溃。", "Sinking underwater, Reaching for surface, Drowning, Suffocation, Deep blue", "Low"),
  l("371", "破碎的镜子 (Shattered Mirror)", "【自我崩塌/精神分裂】 镜子碎裂，映出无数个角色的碎片。隐喻自我认知的破碎、精神崩溃或多重人格。", "Shattered mirror, Broken reflection, Fragmented face, Identity crisis", "Low"),
  l("372", "风中残烛 (Flickering Candle)", "【脆弱/生命垂危】 蜡烛在风中剧烈摇曳，几乎熄灭。隐喻生命的脆弱、最后的希望或即将到来的黑暗。", "Flickering candle, Wind blowing flame, Dying light, Fragility", "Low"),
  l("373", "迷宫俯瞰 (Maze Overview)", "【困惑/人生难题】 俯视迷宫，角色像蚂蚁一样在其中寻找出口。隐喻人生的迷茫、复杂的局势或无法解决的难题。", "Maze from above, Labyrinth, Lost character, Confusion, Puzzle", "Low"),
  l("374", "多米诺骨牌 (Domino Fall)", "【因果/连锁反应】 推倒第一块骨牌，引发连锁倒塌。隐喻一个小事件引发的巨大灾难或不可逆转的局势。", "Domino effect, Falling dominoes, Chain reaction, Inevitability", "Low"),
  l("375", "悬崖边缘 (Cliff Edge)", "【危机/抉择/绝境】 角色站在悬崖最边缘，脚下是深渊。隐喻处于人生的转折点、极度的危险或生死抉择。", "Standing on cliff edge, Abyss below, Precipice, Danger, Decision point", "Low"),
  l("376", "且听风吟 (Wind Blowing Grass)", "【宁静/时间/虚无】 大风吹过草原或麦田，形成波浪。隐喻看不见的力量（命运/时间）在推动万物，或暴风雨前的宁静。", "Wind blowing grass, Wheat field waves, Invisible force, Serenity, Nature power", "Low"),
  l("377", "孤灯 (Lonely Streetlight)", "【孤独/等待/希望】 漆黑的街道只有一盏路灯亮着。隐喻绝望中的一点希望，或孤独的守望者。", "Single streetlight, Dark street, Cone of light, Loneliness, Solitude", "Low"),
  l("378", "面具掉落 (Mask Falling)", "【真相/虚伪/脆弱】 角色摘下面具（或是面具碎裂），露出真容（通常是哭泣或狰狞）。隐喻伪装的卸下。", "Mask falling off, Cracked mask, Revealing true face, Hypocrisy end", "Low"),
  l("379", "逆流而上的鱼 (Fish Upstream)", "【奋斗/坚持/反叛】 一条鱼逆着湍急的水流向上游。隐喻不屈的意志、逆天改命或反抗主流。", "Salmon swimming upstream, Fighting current, Struggle, Perseverance", "Low"),
  l("380", "腐烂的苹果 (Rotting Fruit)", "【堕落/变质/阴暗面】 外表完美的苹果内部有虫子，或快速腐烂。隐喻美好的表象下隐藏的罪恶或腐败。", "Rotting apple, Worm inside fruit, Decay, Corruption, Hidden evil", "Low"),
  l("381", "提灯探路 (Lantern in Dark)", "【探索/求知/先驱】 角色提着灯在迷雾或黑暗中前行。隐喻在未知中寻找真理，或作为引导者。", "Holding lantern, Walking in fog, Guiding light, Discovery", "Low"),
  l("382", "断线的风筝 (Kite Flying Away)", "【失去/失控/告别】 风筝线断了，风筝飘远。隐喻失去控制、童年的逝去或无法挽回的离别。", "Kite string breaking, Kite flying away, Loss, Letting go", "Low"),
  l("383", "时钟倒转 (Clock Spinning Back)", "【后悔/回忆/修正】 时钟指针飞速逆时针旋转。隐喻时光倒流的渴望、进入回忆或试图修正错误。", "Clock hands spinning backwards, Time reversal, Regret, Flashback", "Low"),
  l("384", "冰层破裂 (Ice Cracking)", "【危机爆发/脆弱】 脚下的冰层出现裂纹并迅速蔓延。隐喻原本稳定的关系或局势瞬间崩溃，危险迫在眉睫。", "Ice cracking under feet, Fracture lines, Imminent danger, Fragile foundation", "Low"),
  l("385", "两手相触 (Hands Almost Touching)", "【渴望/遗憾/米开朗基罗】 两只手伸向对方，指尖几乎碰到但没碰到。隐喻无法触及的爱、遗憾或神性的传递。", "Hands reaching out, Fingers almost touching, Creation of Adam style, Longing", "Low"),
  l("386", "积灰的玩具 (Dusty Toy)", "【童年逝去/遗忘】 阳光照在积满灰尘的泰迪熊上。隐喻纯真的丧失、被遗忘的过去或时间的无情。", "Dusty teddy bear, Abandoned toy, Sunlight motes, Lost childhood", "Low"),
  l("387", "困兽之斗 (Caged Beast)", "【愤怒/潜力/压抑】 猛兽在笼子里焦躁地踱步，眼神凶狠。隐喻角色内心积压的愤怒或即将爆发的力量。", "Tiger pacing in cage, Angry beast, Suppressed rage, Potential energy", "Low"),
  l("388", "落叶归根 (Falling Leaves)", "【轮回/晚年/平静】 秋叶缓慢飘落到树根旁。隐喻生命的轮回、游子归乡或平静地接受死亡。", "Autumn leaves falling, Circle of life, Return to roots, Peaceful end", "Low"),
  l("389", "牵线木偶剪断 (Cutting Strings)", "【觉醒/自由/反叛】 剪刀剪断控制木偶的线，木偶瘫倒或独立站起。隐喻摆脱控制，获得独立人格。", "Cutting puppet strings, Snap wires, Liberation, Breaking control", "Med"),
  l("390", "红线缠绕 (Red String)", "【缘分/命运/纠缠】 杂乱的红线缠绕在角色身上或手指上。隐喻复杂的命运纠葛、姻缘或无法解开的谜题。", "Red string of fate, Tangled threads, Destiny, Complex relationship", "Low"),
  l("391", "深渊回望 (Abyss Staring)", "【恐惧/同化/尼采】 角色向下看无底深渊，深渊似乎在变大。隐喻凝视罪恶时的心理恐惧，或被黑暗同化。", "Looking into abyss, Dark void, Vertigo, Nietzsche theme", "Low"),
  l("392", "破墙而入的光 (Light Through Crack)", "【希望/救赎/启示】 黑暗的房间墙壁裂开，一道强光射入。隐喻绝望中的一线生机或真理的启示。", "Light beam through crack, Wall breaking, Hope, Divine intervention", "Low"),
  l("393", "被淹没的城市 (Flooded City)", "【末日/记忆/潜意识】 熟悉的城市建筑被水淹没。隐喻旧时代的终结、被淹没的记忆或潜意识的吞噬。", "Flooded city streets, Underwater ruins, Post-apocalyptic, Subconscious", "Low"),
  l("394", "无脸人 (Faceless Crowd)", "【异化/孤独/迷失】 周围的人群都没有五官，或戴着同样的面具。隐喻角色的社交恐惧、异化感或在群体中失去自我。", "Faceless people, Blank faces, Alienation, Social anxiety, Surreal", "Med"),
  l("395", "蝴蝶效应 (Butterfly Flapping)", "【因果/微小/混沌】 一只蝴蝶轻轻扇动翅膀，周围气流开始扰动。隐喻微小的起因将导致巨大的后果。", "Butterfly wings macro, Air disturbance, Chaos theory, Small cause", "Low"),
  l("396", "过山车顶点 (Rollercoaster Top)", "【顶点/恐惧/不可逆】 第一人称视角，过山车爬到最高点停顿的一秒。隐喻事情发展到高潮，即将发生不可逆转的剧变。", "Rollercoaster drop view, Top of peak, Anticipation, Point of no return", "Low"),
  l("397", "破碎的雕像 (Broken Statue)", "【信仰崩塌/文明毁灭】 宏伟的雕像倒在地上碎裂。隐喻旧信仰的崩塌、权力的覆灭或文明的终结。", "Fallen statue, Broken idol, Ruins, End of era, Loss of faith", "Low"),
  l("398", "衔尾蛇 (Ouroboros)", "【循环/永恒/徒劳】 蛇咬住自己的尾巴，形成圆环。隐喻无限循环的时间、宿命或徒劳的努力。", "Snake eating tail, Ouroboros symbol, Infinite loop, Cycle, Eternity", "Med"),
  l("399", "融化的时钟 (Melting Clock)", "【记忆扭曲/时间主观】 达利风格，钟表像饼一样软塌塌地挂着。隐喻记忆的模糊、时间的无意义或梦境状态。", "Melting clock, Dali style, Distorted time, Surreal memory", "Low"),
  l("400", "黎明破晓 (Sunrise Break)", "【新开始/希望/结局】 最黑暗的时刻过去，地平线露出第一缕阳光。隐喻苦难结束，新的希望开始。", "Sunrise horizon, First light, Breaking dawn, New beginning, Hope", "Low")
];

export const getLensById = (id: string) => CORE_LENSES.find(l => l.id === id);

export const getLensesByCategory = () => {
  return {
    "Foundation (001-040)": CORE_LENSES.filter(l => parseInt(l.id) <= 40),
    "Movement (041-080)": CORE_LENSES.filter(l => parseInt(l.id) >= 41 && parseInt(l.id) <= 80),
    "Composition (081-120)": CORE_LENSES.filter(l => parseInt(l.id) >= 81 && parseInt(l.id) <= 120),
    "Lighting (121-160)": CORE_LENSES.filter(l => parseInt(l.id) >= 121 && parseInt(l.id) <= 160),
    "Auteur & Tech (161-200)": CORE_LENSES.filter(l => parseInt(l.id) >= 161 && parseInt(l.id) <= 200),
    "Action & Horror (201-240)": CORE_LENSES.filter(l => parseInt(l.id) >= 201 && parseInt(l.id) <= 240),
    "Sci-Fi & Surreal (241-280)": CORE_LENSES.filter(l => parseInt(l.id) >= 241 && parseInt(l.id) <= 280),
    "Blocking (281-320)": CORE_LENSES.filter(l => parseInt(l.id) >= 281 && parseInt(l.id) <= 320),
    "Transitions (321-360)": CORE_LENSES.filter(l => parseInt(l.id) >= 321 && parseInt(l.id) <= 360),
    "Metaphor (361-400)": CORE_LENSES.filter(l => parseInt(l.id) >= 361 && parseInt(l.id) <= 400),
  };
};



/**
 * Compact lens library for Agent 2 (Visual Director).
 * Only ID + English name + keywords. ~12K tokens vs ~50K full.
 */
export const toCompactLensLibrary = (): string => {
  return CORE_LENSES.map(l => {
    const engName = l.name.replace(/^[^(]*\(/, '').replace(/\)$/, '');
    return `[${l.id}] ${engName} | ${l.keywords}`;
  }).join('\n');
};

/**
 * Detailed lens library for Agent 3 (Asset Producer).
 * Only expands the Lens entries that Agent 2 actually selected.
 */
export const toDetailedLensLibrary = (shotIds: string[]): string => {
  const idSet = new Set(shotIds.map(id => id.padStart(3, '0')));
  const matched = CORE_LENSES.filter(l => idSet.has(l.id));
  if (matched.length === 0) {
    return toCompactLensLibrary();
  }
  return matched.map(l =>
    `[${l.id}] ${l.name}: ${l.description} (Keywords: ${l.keywords})`
  ).join('\n');
};
export const LENS_LIBRARY_PROMPT = `
**CORE LENS LIBRARY (Full Reference - 400 Shots)**:
Part 1: Foundation (001-040) - Framing & Angle
Part 2: Movement (041-080) - Camera Dynamics
Part 3: Composition (081-120) - Staging
Part 4: Lighting (121-160) - Atmosphere & Color
Part 5: Auteur Styles & Tech (161-200) - Director Signatures & Camera Specs
Part 6: Genre: Action & Horror (201-240) - Kinetic Energy & Fear
Part 7: Sci-Fi & Surrealism (241-280) - Spectacle & Dream Logic
Part 8: Advanced Blocking (281-320) - Choreography & Staging
Part 9: Transitions & Editing (321-360) - Visual Continuity
Part 10: Metaphor (361-400) - Visual Synesthesia (Critical for "Spectacle")

Examples:
[001] Extreme Close-Up: Intense detail/pressure.
[004] Choker Shot: Anxiety/Suffocation.
[022] Low Angle: Heroic/Dominant.
[060] Dolly Zoom: Vertigo/Realization.
[165] Bayhem 360: Epic hero moment.
[213] Silhouette Fight: Stylized combat.
[256] Inception Fold: City bending.
[321] Graphic Match: Shape-based transition.
[392] Light Through Crack: Hope in darkness.
[395] Butterfly Effect: Small cause, chaos.
`;
